### ISSUE TITLE
incomplete support for cvxopt 1.1.7

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1018]
Fails only on Windows 7 on gas_solar_trade testing, presumably because that's the only test server using cvxopt 1.1.7.
https://acdl.mit.edu/csi/job/gpkit_ResearchModel_gas_solar_trade_Push/36/

**Comment by galbramc** [comment]
So does this mean that your cvxopt minimum version is now 1.1.9? Should the documentation and setup script reflect this?

**Comment by bqpd** [comment]
I don't know! So far cvxopt runs all the other models just fine, so it's only this one research model that finds itself in a hairy corner. We might as well move in that direction, though?

I don't think the setup script mentions the cvxopt version (though I guess the build script could raise a warning).
