### ISSUE TITLE
document as_gpconstr, as_posyslt1

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#1036]
I find the name `as_gpconstr` confusing and misleading (it can return Signomials, if I understand correctly).

What about `as_constraint_set`? Wouldn't that be more precise?

**Comment by bqpd** [comment]
`as_gpconstr` cannot return Signomial constraints.

**Comment by whoburg** [comment]
Maybe we need to update the docstrings a bit. I keep getting confused about the distinction between `as_gpconstr` and `as_posyslt1`.

**Comment by bqpd** [comment]
Yeah, those should definitely be better documented.

The reasoning behind the names is that `gpconstr` is short for `GP-compatible ConstraintSet`, which is what that method returns, while `as_posyslt1` returns a list of Posynomials.
