### ISSUE TITLE
Wanted: a simple, clean example of building a modular model

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#1057]
Something like the Multipoint analysis modeling example, but simpler and cleaner and more uniformly structured.

**Comment by bqpd** [comment]
It would be helpful to know what parts of the multipoint example you find least simple and clear and most heterogeneously structured!

**Comment by pgkirsch** [comment]
I think a simpler example wouldn't deal with multi-point analysis. Also, and maybe this is picky, but doing something like `objective = ` and `constraints = ` would be helpful, particularly when trying to interpret return statements.

Maybe this is more of a question about the syntax but it's not super clear why it's ok not to return things in models without constraints. More importantly, it's also not clear why it's ok to return `<objective>, <constraints>` and also just `<constraints>`. It might be gross but it would be way more consistent to return `None, <constraints>` in the case where there is no objective.

Is the line `self.weight = W` necessary? Couldn't it be omitted and the line `aircraft.weight ...` be replaced with `aircraft['W']...`?

The `setup` method is before the `dynamic` method in the `Aircraft` model, but the opposite is true in the `Wing` model.

The multi-point example would also benefit from `AircraftP` becoming `AircraftPerformance`.

**Comment by bqpd** [comment]
First things first, you can't return `objective, constraints`...if you want to set the cost of a model you have to explicitly set `self.cost`

**Comment by bqpd** [comment]
The trick with `aircraft['W']` is thorny, and advice would be welcome! The trick is that aircraft's submodels contain other variables named `W`, such that `aircraft['W']` is actually an ambiguous reference...

**Comment by bqpd** [comment]
Good points on the naming!

**Comment by pgkirsch** [comment]
Oh, sorry... so what is the interpretation of `return self.components, [W >= sum(c["W"] for c in self.components)]`? And ` return self.flightstate, self.aircraftp`?

**Comment by bqpd** [comment]
Ah, sorry. Those are lists of constraints, equivalent to e.g. `return (self.components, [W >= sum(c["W"] for c in self.components)])`

**Comment by pgkirsch** [comment]
It also takes a lot of jumping around to see what the `self.perf_models` constraints actually look like (i.e. `perf_models` --> `wing_aero` --> `aircraft.wing` --> `class Wing` -->  `class WingAero`).

**Comment by pgkirsch** [comment]
I think it's really important to remember (as I was telling @whoburg) that to get buy-in from people who aren't familiar with GP or GPkit or even python, there needs to be as little code complexity as possible. People *really* like the whole "it's just a list of constraints" thing. That example is anything but "just a list of constraints".

**Comment by lochieferrier** [comment]
@pgkirsch Apart from code complexity and install time, are there any other issues you can think of that discourage people from trying out GP? Useful to hear this from someone in industry, MIT often isn't well enough exposed.

**Comment by bqpd** [comment]
@mjburton11, I think there's an awesome opportunity to do this as part of publishing and documenting the `gas_solar_trade` shared code on`gpkitmodels`.
