### ISSUE TITLE
a better, faster, A matrix

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#1065]
might be a repeat issue but I couldn't find any others.

We should avoid rebuilding the model for each GP solve while solving an SP. Drela thinks this should be a top priority.

**Comment by whoburg** [comment]
@whoburg thinks this should be a top priority too

**Comment by whoburg** [comment]
What's a working AP model that we could use as a test case for this? Link and commit hash?

**Comment by mayork** [comment]
engine test function would be good. very stable, decently large.

**Comment by edfan** [comment]
@mayork, could I get a link?

Ran cProfile on d8_eng_wing last night- seems to be spending >99% of time in cvxopt code (output is attached). Will reprofile with MOSEK/different hardware soon.

[d8_eng_wing.cprof.zip](https://github.com/hoburg/gpkit/files/997102/d8_eng_wing.cprof.zip)

**Comment by mayork** [comment]
for the large models only run them with Mosek. The fully integrated D8 takes 111 minutes to solve on cvxopt and only 30 sec on Mosek.

this is a good file to try: https://github.com/hoburg/turbofan/blob/master/turbofan/engine_flight_profile_fleet.py

Also, the function `run_D82` in `SP_aircraft.py` would be good to profile: https://github.com/hoburg/d8/blob/master/SP_aircraft.py

**Comment by edfan** [comment]
Wow, that's a pretty incredible difference. The turbofan model breaks Mosek for me (with `ImportError('cannot import name expopt_h',)`, but I suspect that's related to issues with my Mosek install- had to play around with the DYLIB_LIBRARY_PATH envvar to get it to work at all. D8 currently breaks along the lines of hoburg/d8#65.

**Comment by mayork** [comment]
yeah i think it's a mosek install error for you, turbofan is passing all tests currently

**Comment by mayork** [comment]
getting close to having a paper done...a major aspect of which is touting the speed of the D8 model so it'd really be great if we could get this going and shave some time

**Comment by bqpd** [comment]
@edfan, you're on a Mac, then? Did the install instructions for MOSEK on mac not work on your computer?

**Comment by edfan** [comment]
I had to manually add MOSEK's dynamic libraries to my path- they were not being picked up automatically. At this point, `import mosek` works, all of the GPkit tests pass, and most models seem to work.

**Comment by bqpd** [comment]
Huh, what's `import sys; print sys.platform` show for you? The gpkit build script should use `install_name_tool` to prevent the need for a global DYLIB hack.

**Comment by edfan** [comment]
Yep, it's `darwin`. [Here's the output of rebuild()](https://gist.github.com/edfan/c14e4ec8effc0489b187783630ce36bf).

**Comment by bqpd** [comment]
So it did run `install_name_tool` without errors. And `/Users/edwardf/mosek/7/tools/platform/osx64x86/bin/libmosek64.7.1.dylib /Users/edwardf/.gpkit/expopt.so` certainly looks like a likely path for the mosek library / our expopt library.

**Comment by bqpd** [comment]
Odd.

**Comment by edfan** [comment]
Finally got everything working- my guess was that it was caused by some issue with pip conflicts. Had to manually `sudo rm -rf /usr/local/lib/python2.7/site-packages/gpkit`- afterwards, reinstalling with setup.py worked.

Will be working on this over the next few days, then will pick up again after finals. @mayork, do you have a specific timeframe in mind?

**Comment by bqpd** [comment]
@edfan, thinking about this, part of the problem will come down to distinguishing signomial programs from generic sequential geometric programs. One simple way to do this could be to iterate through `sp.flat()` and pull signomial constraints out, construct a new gp and iterate on it, editing its A matrix by using the pulled-out constraints.

**Comment by edfan** [comment]
Reprofiled with MOSEK on `turbofan/engine_flight_profile_fleet.py`. 77% of time spent in `signomial_program.py:156 (gp)`, compared to 7% in `geometric_program.py:92 (solve)`.

[engine_flight_profile_fleet.cprof.zip](https://github.com/hoburg/gpkit/files/1008536/engine_flight_profile_fleet.cprof.zip)

([SnakeViz](https://jiffyclub.github.io/snakeviz/) is nice to look at these.)

**Comment by bqpd** [comment]
Nice, that's pretty! Maybe worth including in our research-model tests as well. I've mostly been using the line_profiler for tracking down individual bottlenecks.

**Comment by bqpd** [comment]
(been using snakeviz a bit, it's as good as it looks)

re: editing genA, the issue gets confused by a couple of core GPkit features: substitutions/sensitivities and unordered monomials. If we want to edit the A matrix directly, we're going to need to use it to determine sensitivities, and make it easier to edit on a posynomial-by-posynomial basis.

**Comment by bqpd** [comment]
the nomialmap refactor makes it clear that genA is the current bottleneck; generating the A matrix for each solve takes ~12% of total time.
