### ISSUE TITLE
automatically draw tree diagram of named models

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1088]
after @1ozturkbe 
(also show the variables which are drawn upwards?)

**Comment by 1ozturkbe** [comment]
<img width="792" alt="treediagram" src="https://cloud.githubusercontent.com/assets/15684191/25634821/ffae6a62-2f49-11e7-9e6b-2d46551fc5a1.PNG">
This is somewhat inspired by the variable linking diagrams that were originally created by Philippe. The idea is that it would help a designer easily determine where new/existing constraints would belong, by looking at the variables that they reference from each model.

**Comment by 1ozturkbe** [comment]
Here is the picture of the board from my discussion today with Ned. May be a little disorganized, but with some visual memory Ned and I can decipher it :P 
![2017-05-02 15 02 05](https://cloud.githubusercontent.com/assets/15684191/25634938/650e9206-2f4a-11e7-89bd-714dc3f4cdc8.jpg)

**Comment by pgkirsch** [comment]
I've previously done this with sunburst plots but propose using [plotly treemaps](https://plotly.com/python/treemaps/) instead, with option to size rectangles by number of constraints.

**Comment by bqpd** [comment]
oh that sounds good. Sizing by:

  - number of constraints
  - sensitivity
  - number of variables
  - number of freevariables?
