### ISSUE TITLE
clarify when substituting zero is OK

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#1099]
We need to clarify for our users when, if ever, substituting the value 0 for a variable is ok.

Currently, the behavior as I understand it is:

 - substituting 0 into a monomial: not allowed
 - substituting 0 into a posynomial: allowed if the result is nonzero

This behavior roughly carries over to Models and GPs: substituting a zero works when the variable appears only in Posynomials, and usually fails (with a variety of possible errors) if the variable appears in any monomial constraints.

The current behavior is not easy to understand, and seems a bit fragile. This is further illustrated with the examples below.

In this first model, substituting zero is fine. `x` appears only in a posynomial, so substituting zero is equivalent to removing that term from the posynomial.
```python
from gpkit import Variable, Model

x = Variable("x")
y = Variable("y")

m = Model(y, [
              y >= x + y**0.5,
             ])
m.substitutions.update({x: 0})
sol = m.solve()
print sol.table()
```

In this next example, the only change is that `x` appears in an equality constraint `x == z`:
```python
from gpkit import Variable, Model

x = Variable("x")
y = Variable("y")
z = Variable("z")

m = Model(y, [
              y >= x + y**0.5,
              x == z,
             ])
m.substitutions.update({x: 0})
sol = m.solve()
print sol.table()
```
GPkit correctly identifies that `z has no lower bound`. cvxopt raises a RankError, and mosek fails with `RuntimeWarning: Primal solution violates constraint: inf is greater than 1`.

Note: it's tempting in the above example to have GPkit identify that `z` must also be zero, but this seems fragile unless the monomial has only one free Variable remaining post-substitution. To see why, imagine the constraint were instead `x == z1*z2`. Now either `z1` or `z2` must be zero, but it's not clear which one.

Now for a few more examples of the current behavior:

Attempting to substitute zero into a Monomial equality constraint:
```python
In [33]: (x == z).sub({x: 0})
ValueError: each c must be positive.
```

Successfully substituting zero into a posynomial constraint:
```python
In [34]: (y >= x + z**2).sub({x: 0})
Out[34]: gpkit.PosynomialInequality(y >= z**2)
```
Using `Model.subinplace` instead of `substitutions.update` results in a potentially confusing error about Signomials:
```python
from gpkit import Variable, Model

x = Variable("x")
y = Variable("y")
z = Variable("z")

m = Model(y, [
              y >= x + y**0.5,
              x == z,
             ])
m.subinplace({x: 0})
sol = m.solve("cvxopt")
print sol.table()
```
```ValueError: GeometricPrograms cannot contain Signomials.```

**Comment by whoburg** [comment]
One other relevant tool for this discussion is our `Model.zero_lower_unbounded_variables()` method, which recursively sets variables that don't have a lower bound to zero.

I'm tempted to call that automatically for all models presolve. But this has a big downside: modeling errors that leave variables unbounded below (which are quite common) would be quietly ignored. Maybe we can come up with something more limited that only zeroes variables if certain conditions are met?

**Comment by bqpd** [comment]
It's much simpler, I think: substituting zero is allowed when it creates only tautological constraints.

**Comment by bqpd** [comment]
`subinplace` should not be used for numbers, it doesn't have the same behaviour as solving

**Comment by bqpd** [comment]
@whoburg, what should be done to resolve this issue?
  - document zero-substitutions and tautological/impossible constraint errors
  - document `zero_lower_unbounded_variables()`
  - anything else?

**Comment by whoburg** [comment]
- document more clearly when, if ever, substituting the value 0 for a variable is ok. Needs to be clear for users who don't know apriori what `valid or tautological` means.
 - consider possible changes to `zero_lower_unbounded_variables`, as suggested above.
More detail below.

I opened this ticket because a user tried to do the following. He defined the variables
```python
m_fuel = Variable("m_{fuel}", "lb", "fuel mass")
h_fuel = Variable("h_{fuel}", 43, "MJ/kg", "fuel specific energy")
E_fuel = Variable("E_{fuel}", "MJ", "fuel energy")
```
He included the constraint `E_fuel == h_fuel * m_fuel` in a model, and then substituted m_fuel=0, expecting that E_fuel=0 would follow (i.e. would be derived). Instead, a confusing error occurred.

Key issues to address are:
 - Decide: should we support what the user tried to do? If so, the cleanest path I see to implementation is to modify `zero_lower_unbounded_variables` such that it only zeroes variables that appear in constraints involving zero substitutions (this will allow helpful "var has no lower bound" warnings to still get raised). That way, we could always call `zero_lower_unbounded_variables` under the hood presolve. Disadvantages: less transparent, and risk of encouraging users to substitute 0 in cases where we can't support it (e.g. consider a monomial constraint `A==B*C` where none of A,B,C are constants. If A is zero-substituted, we can't zero B or C.
 - Document: suggested best practices for zero-substitutions

**Comment by bqpd** [comment]
We should deprecate substituting 0, I think.
