### ISSUE TITLE
Documentation of SP solution heuristic

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#1101]
is the SP solution heuristic documented in any write up, paper, etc.?

**Comment by bqpd** [comment]
It had a cameo in the SP equality paper, but I can do a write-up with you if you need one.

**Comment by 1ozturkbe** [comment]
Ali and I were wondering the same thing for the robust SP paper we were writing, especially since we had to rewrite the SP solver. We should definitely have some documentation.

**Comment by bqpd** [comment]
covered by #207
