### ISSUE TITLE
update / install error

### ISSUE THREAD

**Issue by mopg** [convexengineering/gpkit#1105]

**Comment by mopg** [comment]
I just pulled gpkit to the latest version, but after I installed it using `pip install -e gpkit`, none of the solves work anymore. 

For the simple example from the website:
`"Very simple problem: minimize x while keeping x greater than 1."
from gpkit import Variable, Model

# Decision variable
x = Variable("x")

# Constraint
constraints = [x >= 1]

# Objective (to minimize)
objective = x

# Formulate the Model
m = Model(objective, constraints)

# Solve the Model
sol = m.solve(verbosity=1,solver='cvxopt')

# print selected results
print("Optimal cost:  %s" % sol["cost"])
print("Optimal x val: %s" % sol(x))`

The output I get is:
`Using solver 'cvxopt'
Solving for 1 variables.
Traceback (most recent call last):
  File "example.py", line 17, in <module>
    sol = m.solve(verbosity=1,solver='cvxopt')
  File "/home/mopg/code/gpkit/gpkit/constraints/prog_factories.py", line 81, in solvefn
    result = solvefn(solver, verbosity, *args, **kwargs)
  File "/home/mopg/code/gpkit/gpkit/geometric_program.py", line 188, in solve
    k=self.k, *args, **kwargs)
  File "/home/mopg/code/gpkit/gpkit/_cvxopt.py", line 44, in cvxoptimize
    solution = gpsolver(k, F, g, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/cvxopt/cvxprog.py", line 2161, in gp
  File "build/bdist.linux-x86_64/egg/cvxopt/cvxprog.py", line 1966, in cp
  File "build/bdist.linux-x86_64/egg/cvxopt/cvxprog.py", line 778, in cpl
  File "build/bdist.linux-x86_64/egg/cvxopt/cvxprog.py", line 1901, in kktsolver_e
  File "build/bdist.linux-x86_64/egg/cvxopt/cvxprog.py", line 1893, in kktsolver
  File "build/bdist.linux-x86_64/egg/cvxopt/misc.py", line 1099, in factor
ValueError: -7`

With mosek the output is `final status of solver 'mosek' was 'UNKNOWN', not 'optimal'.

When I try reverting to older versions (which worked before), I get the same issues, so I'm probably doing something not particularly intelligent.

Any thoughts about what could be causing this?

**Comment by 1ozturkbe** [comment]
Just as a note, we tried using Bounded and debug(), neither were useful. It's also funny that the output said that the solver was solving for 2 variables, not 1. So I assume that the 'ghost variable' is blowing up? Don't really understand what is happening.

**Comment by bqpd** [comment]
Ooh this is an interesting one. It looks kinda like your cvxopt install broke somehow? Try reinstalling that, then un/reinstalling gpkit maybe.

(side note: you shouldn't need to `pip install -e gpkit` after redownloading, it just installs a shortcut to that directory)

**Comment by mopg** [comment]
cvxopt was working before (I use it for another code). But I reinstalled it anyway (it is version 1.1.8 btw, also tried with 1.1.9 but I get the same error), then removed my entire gpkit directory and cloned it again. But no luck, I keep getting that same error (ValueError: -7).

So outside of gpkit cvxopt works fine.

**Comment by mopg** [comment]
So I got it working on my Mac with cvxopt, so that at least let's me continue. 

Still don't know what is causing the other issues with mosek on my mac and with mosek and cvxopt on my desktop.

**Comment by bqpd** [comment]
What a bizarre error for cvxopt to return. I'll look into it.
