### ISSUE TITLE
GPkit tests fail after installing MOSEK

### ISSUE THREAD

**Issue by chriscourtin** [convexengineering/gpkit#1136]
63/179 tests fail when running gpkit.tests.run() after installing MOSEK on Windows 7.  I tried rebuilding/reinstalling gpkit per the instructions on the installation page.   Running gcc or python -c 'import("mosek").Env() doesn't return an error.   Mosek 8.0 is installed, using a floating license server.   Test outputs are attached. 
[gpkit_test_results.txt](https://github.com/hoburg/gpkit/files/1149628/gpkit_test_results.txt)

**Comment by bqpd** [comment]
This looks like some kind of error with accessing temporary directories on windows, where the mosek_cli solver is solving but then does not find the solution file in the temporary directory that was created, which is odd...

**Comment by bqpd** [comment]
If you want to use the `mosek_cli` solver in particular, you could specify the directory for it to put the `.eo` and `.sol` files into.

**Comment by whoburg** [comment]
@chriscourtin, to see if @bqpd's theory is correct, maybe try editing `gpkit/env/settings` to remove `mosek_cli` from the list of solvers (but keep `mosek`). Not sure whether this requires a rebuild. Check if all tests pass after `mosek_cli` is dropped.

**Comment by bqpd** [comment]
It looks like this was the same thing as Will saw in https://github.com/convexengineering/gpkit/issues/1153, and is fixed by the modifications to mosek_cli mentioned there.
