### ISSUE TITLE
unit tests produce RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#1140]
Let's prioritize fixing this, I've seen it occur for our Learn3 users and it's quite unsettling for them.

```python
﻿﻿gpkit/nomials/data.py:186: RuntimeWarning: invalid value encountered in double_scalars
  mmap[i][j] = mag(expmap[exp][j]/c)
```

Once fixed, @galbramc should enable parsing the logs for `RuntimeWarning`s

**Comment by galbramc** [comment]
It happens in models as well:

gas_solar_trade/gassolar/environment/solar_irradiance.py:40: RuntimeWarning: overflow encountered in exp
  tau = np.exp(-0.175/costhsun)

overflow is also not a good thing. I really don't know why these things are not considered errors by numpy.

**Comment by bqpd** [comment]
This is what numpy does anytime it casts to inf or nan, I think. I can fix the one in data caused by a 0-monomial, but it's generally a useful message.

**Comment by galbramc** [comment]
I just saw this in my email. I'm still confused by how it uses the nan and just continues going. Why isn't fine final answer a nan? Where does the nan disappear so that it is not relevant in the computation?

**Comment by bqpd** [comment]
I think this one in particular is creating an inf, which ends up on the greater-than side of a constraint and so makes the constraint trivially easy.

**Comment by galbramc** [comment]
So is that legitimate behavior? Are you explicitly trying to test for that? I don't think it belongs in the testing if this is a mere accident. If you want to allow inf to be an upper bound, then you should have a test that checks that explicitly.

**Comment by bqpd** [comment]
If it results in a valid constraint, I'm tempted to let users get away with it...but probably raising an error in such instances wouldn't inconvenience them too much.

**Comment by bqpd** [comment]
In the Learn3 case I bet it's because of a 0-substitution, which is a whole 'nother unexpected use case that we should probably make a better interface for.

**Comment by galbramc** [comment]
Yeah, I don't know how reliable things are in regards to relying on NaN or Inf. Neither one is really a number, and something about working with non numbers in a numerical calculations makes me uneasy.

**Comment by bqpd** [comment]
This shouldn't happen anymore with NomialMap
