### ISSUE TITLE
model.program._compile_result() broken

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#1142]
The error message for `unknown` suggests using `model.program._compile_result()` to access the latest variable values, however this is currently not working because `solver_out` has no key `"nu"`. Workaround is to change `nu, la = solver_out["nu"], solver_out["la"]` to `la = solver_out["la"]`.

Unfortunately, that breaks the sensitivities part of `_compile_result` (not super important to me, I can just comment it out but probably should be addressed).

**Comment by bqpd** [comment]
Oops, good point. Fixed in #1221
