### ISSUE TITLE
GP attributes overwritten inside SP m.program

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#1144]
It's possible that I doing this wrong but what I want to do is access the cost of a single gp within an SP. I tried this with two methods:

```python
solver_out = m.program.gps[-1].solver_out
sol = m.program.gps[-1]._compile_result(solver_out)
sol['cost']
 solver_out = m.program.gps[0].solver_out
 sol = m.program.gps[0]._compile_result(solver_out)
sol['cost']
```
and 
```python
m.program.gps[0].solver_out['objective']    
m.program.gps[-1].solver_out['objective']    
```

You'll note that I was checking the first and last GP iteration for cost. However, the cost was always equal to the final cost of 30465.218441797493. 

I did verify there are 7 GP solves so this isn't something weird where index -1 and 0 are the same. I also checked all the intermediate costs by going `m.program.gps[i].solver_out['objective']` for i 0:6 and they were all equal to the same thing.

The code that I was running is at https://github.com/hoburg/SPaircraft/pull/93/commits/e6b94c200cb8833c9c64e26d7fad0fe108ee5eb3. 

@bqpd @pgkirsch

**Comment by mayork** [comment]
@whoburg going to tag you in this too since we need it for the SPAJOA paper

**Comment by pgkirsch** [comment]
@mayork Can you not used `plot_convergence` from `gpkit.interactive.plotting`? That's how I made the original plot (see make.py in SPAJOA).

**Comment by mayork** [comment]
@pgkirsch that uses the same underlying technique and outputs the same flawed data

[Screen Shot 2017-08-09 at 10.35.59 AM.PDF](https://github.com/hoburg/gpkit/files/1211989/Screen.Shot.2017-08-09.at.10.35.59.AM.PDF)

@bqpd @whoburg bump

**Comment by mayork** [comment]
@pgkirsch @bqpd @1ozturkbe @whoburg 

It looks like every attribute of each GP inside m.program is being overwritten and is set equal to the value in the last GP iteration. Here is an ipython session I ran that I think confirms this.

```python
solver_out = m.program.gps[-1].solver_out
m.program.gps[-1]._generate_nula(solver_out)
result_N = m.program.gps[-1]._compile_result(solver_out)

solver_out = m.program.gps[0].solver_out
m.program.gps[0]._generate_nula(solver_out)
result_0 = m.program.gps[0]._compile_result(solver_out)

result_N('b')
Out[11]: 35.813999962496275

result_0('b')
Out[12]: 35.813999962496275

result_0('D')
Out[13]: array([[ 28987.76995138], [ 28875.74590713]])

result_N('D')
Out[14]:  array([[ 28987.76995138], [ 28875.74590713]])

result_N('B')
Out[15]: 14.061868119311365

result_0('B')
Out[16]: 14.061868119311365

result_0('I_{z_{wing}}')
Out[17]: array([  1.49002926e+09])

 result_N('I_{z_{wing}}')
Out[18]: array([  1.49002926e+09])
```
To be able to make the convergence plot for the journal paper we really need this functionality working. @bqpd @whoburg thoughts on what to do?

**Comment by mayork** [comment]
@pgkirsch @bqpd @whoburg @1ozturkbe bump on this, updated manuscript for this paper is due in 7 days.

**Comment by pgkirsch** [comment]
@mayork I looked at the code (`constraints/signomial_program.py`) and this doesn't appear to be a bug. Solving the model with `modifylastgp=False` resolves this issue.

```python
In [1]: from gpkit import Variable, Model, SignomialsEnabled

In [2]: x = Variable('x'); y = Variable('y');

In [3]: with SignomialsEnabled():
    m = Model(x, [x + y >= 1, y <= 0.1])
   ...:     

In [4]: sol = m.localsolve()
Beginning signomial solve.
Solving took 4 GP solves and 0.181 seconds.

In [5]: for gp in m.program.gps:
    print gp.result['cost']
   ...:     
0.900000000066
0.900000000066
0.900000000066
0.900000000066

In [6]: sol = m.localsolve(modifylastgp=False)
Beginning signomial solve.
Solving took 4 GP solves and 0.0698 seconds.

In [7]: for gp in m.program.gps:
    print gp.result['cost']
   ...:     
2.5
0.925481467987
0.900034463391
0.900000000066
```


@bqpd is there a reason you choose to have the default be `modifylastgp=True`?

**Comment by pgkirsch** [comment]
@bqpd Does `modifylastgp` have implications for speed?

**Comment by mayork** [comment]
@pgkirsch ah I really thought this was a bug. I used to access GP solves all the time with the above method. I bet Ned changed this during his push to speed things up. 

@bqpd if this is intentional now you can close the issue

**Comment by bqpd** [comment]
Yeah, this is intentional...there's a new `self.results` that includes the raw GP solution, which should work for this use.

@pgkirsch yes, `modifylastgp=False` is much slower

**Comment by mayork** [comment]
@bqpd working on a paper revision and the modifylastgp=False isn't preventing the solution from being overwritten. Did this implementation change somehow?

**Comment by mayork** [comment]
@1ozturkbe

**Comment by mayork** [comment]
@pgkirsch just in case you use this at work ever and know what's going on

**Comment by mayork** [comment]
the argument is now mutategp....took me a while to find this because signomial_program.py is now sgp.py.

**Comment by bqpd** [comment]
ah, yup. sorry for the hassle!
