### ISSUE TITLE
windows 7 @ aurora bugs

### ISSUE THREAD

**Issue by wthalheimer** [convexengineering/gpkit#1153]
Errors:
  1. mosek doesn't build, hanging uninterupptably after complaining about header syntax issues
  2. mosek_cli doesn't work with paths that have dots in their names
  3. cvxopt takes like 10 seconds to import? needs profiling
  4. tests take forever; is this in mosek_cli?

----

edited `cli_expopt.py`:

```python
def imize_fn(path=None, clearfiles=False):  # 8/25, Ned: clearfiles was True
    """Constructor for the MOSEK CLI solver function.

    Arguments
    ---------
    path : str (optional)
        The directory in which to put the MOSEK CLI input/output files.
        By default uses a system-appropriate temp directory.
    """
    if not path:
        path = "C:\\gpkit" # 8/25, Ned: TERRIBLE HACK, WAS tempfile.mkdtemp()
    filename = path + os.sep + "gpkit_mosek"
    if "mosek_bin_dir" in settings and settings["mosek_bin_dir"] not in os.environ['PATH']:
        os.environ['PATH'] = ":".join([os.environ['PATH'],
                                       settings["mosek_bin_dir"]])
```

**Comment by mayork** [comment]
@wthalheimer are you using mosek 7 or 8?

**Comment by wthalheimer** [comment]
@mayork I'm using 8, just freshly downloaded from the link in the docs

**Comment by mayork** [comment]
@wthalheimer cool just curious. debugging a separate issue rn.

**Comment by bqpd** [comment]
I'm thinking that MOSEK 8 might be having some weird constant-offset in solve time :-/

@wthalheimer @mayork try MOSEK 7? https://www.mosek.com/downloads/list/7/

**Comment by mayork** [comment]
@bqpd i'm still on mosek 7...all I did was update license, not reinstall

**Comment by bqpd** [comment]
Weird...

**Comment by mayork** [comment]
@bqpd have you experienced the slow down?

**Comment by bqpd** [comment]
I didn't notice if so. Let's move discussion to the other thread
