### ISSUE TITLE
All mosek tests work, but mosek does not work with simple file

### ISSUE THREAD

**Issue by wthalheimer** [convexengineering/gpkit#1161]
All gpkit unit tests are running on my Windows machine, including those with mosek.

When I try to run from the Anaconda prompt: `python myfile.py`, I get the following error message:

```
Traceback (most recent call last):
  File "C:/Users/thalheimer.william/dev/eVTOL_gpkit/eVTOL.py", line 21, in <module>
    sol = test.solve("mosek",verbosity=0)
  File "C:\Users\thalheimer.william\AppData\Local\Continuum\Anaconda2\lib\site-packages\gpkit\gpkit\constraints\prog_factories.py", line 83, in solvefn
    result = solvefn(solver, verbosity, *args, **kwargs)
  File "C:\Users\thalheimer.william\AppData\Local\Continuum\Anaconda2\lib\site-packages\gpkit\gpkit\constraints\geometric_program.py", line 159, in solve
    solverfn, solvername = _get_solver(solver)
  File "C:\Users\thalheimer.william\AppData\Local\Continuum\Anaconda2\lib\site-packages\gpkit\gpkit\constraints\geometric_program.py", line 150, in _get_solver
    from .._mosek import expopt
  File "C:\Users\thalheimer.william\AppData\Local\Continuum\Anaconda2\lib\site-packages\gpkit\gpkit\_mosek\expopt.py", line 22, in <module>
    raise ImportError("Could not load MOSEK library: "+repr(e))
ImportError: Could not load MOSEK library: ImportError('cannot import name expopt_h',)
```

When I open the expopt.py file, my IDE highlights ".lib" on line 20 as being an unresolved reference.

Any thoughts?

**Comment by bqpd** [comment]
Are the tests with `mosek` running, or just the tests with `mosek_cli`?

**Comment by wthalheimer** [comment]
All the tests that run when I do `python -c "import gpkit.tests; gpkit.tests.run()"` work - so I assume that includes mosek?

**Comment by bqpd** [comment]
I don't believe it does, if this is the setup I did on your computer. Paste
the test output, and try solving with "mosek_cli". (or, better, don't
specify a solver and let gpkit choose the default installed one)

**Comment by wthalheimer** [comment]
Ah ok doesnt work with "mosek_cli" or the default when I run my script.  Below is the output from the unit tests.

test_binary_sweep_tree (gpkit.tests.t_tools.TestTools) ... ok
test_composite_objective (gpkit.tests.t_tools.TestTools) ... ok
test_fmincon_generator (gpkit.tests.t_tools.TestTools)
Test fmincon comparison tool ... ok
test_te_exp_minus1 (gpkit.tests.t_tools.TestTools)
Test Taylor expansion of e^x - 1 ... ok
test_te_secant (gpkit.tests.t_tools.TestTools)
Test Taylor expansion of secant(var) ... ok
test_te_tangent (gpkit.tests.t_tools.TestTools)
Test Taylor expansion of tangent(var) ... ok
test_basic (gpkit.tests.t_sub.TestNomialSubs)
Basic substitution, symbolic ... ok
test_dimensionless_units (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_numeric (gpkit.tests.t_sub.TestNomialSubs)
Basic substitution of numeric value ... ok
test_scalar_units (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_signomial (gpkit.tests.t_sub.TestNomialSubs)
Test Signomial substitution ... ok
test_string_mutation (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_unitless_monomial_sub (gpkit.tests.t_sub.TestNomialSubs)
Tests that dimensionless and undimensioned subs can interact. ... ok
test_variable (gpkit.tests.t_sub.TestNomialSubs)
Test special single-argument substitution for Variable ... ok
test_vector (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_bad_gp_sub (gpkit.tests.t_sub.TestModelSubs) ... ok
test_bad_subinplace (gpkit.tests.t_sub.TestModelSubs) ... ok
test_calcconst (gpkit.tests.t_sub.TestModelSubs) ... ok
test_getkey (gpkit.tests.t_sub.TestModelSubs) ... ok
test_model_composition_units (gpkit.tests.t_sub.TestModelSubs) ... ok
test_model_recursion (gpkit.tests.t_sub.TestModelSubs) ... ok
test_persistence (gpkit.tests.t_sub.TestModelSubs) ... ok
test_phantoms (gpkit.tests.t_sub.TestModelSubs) ... ok
test_quantity_sub (gpkit.tests.t_sub.TestModelSubs) ... ok
test_skipfailures (gpkit.tests.t_sub.TestModelSubs) ... ok
test_united_sub_sweep (gpkit.tests.t_sub.TestModelSubs) ... ok
test_vector_init (gpkit.tests.t_sub.TestModelSubs) ... ok
test_vector_sub (gpkit.tests.t_sub.TestModelSubs) ... ok
test_vector_sweep (gpkit.tests.t_sub.TestModelSubs)
Test sweep involving VectorVariables ... ok
test_dict_key (gpkit.tests.t_vars.TestVarKey)
make sure variables are well-behaved dict keys ... ok
test_eq_neq (gpkit.tests.t_vars.TestVarKey)
Test boolean equality operators ... ok
test_init (gpkit.tests.t_vars.TestVarKey)
Test VarKey initialization ... ok
test_repr (gpkit.tests.t_vars.TestVarKey)
Test __repr__ method ... ok
test_units_attr (gpkit.tests.t_vars.TestVarKey)
Make sure VarKey objects have a units attribute ... ok
test_hash (gpkit.tests.t_vars.TestVariable)
Hashes should collide independent of units ... ok
test_init (gpkit.tests.t_vars.TestVariable)
Test Variable initialization ... ok
test_to (gpkit.tests.t_vars.TestVariable) ... ok
test_unit_parsing (gpkit.tests.t_vars.TestVariable) ... ok
test_value (gpkit.tests.t_vars.TestVariable)
Detailed tests for value kwarg of __init__ ... ok
test_constraint_creation_units (gpkit.tests.t_vars.TestVectorVariable) ... ok
test_init (gpkit.tests.t_vars.TestVectorVariable)
Test VectorVariable initialization ... ok
test_is_vector_variable (gpkit.tests.t_vars.TestArrayVariable) ... ok
test_str (gpkit.tests.t_vars.TestArrayVariable)
Make sure string looks something like a numpy array ... ok
test_shapes (gpkit.tests.t_vars.TestVectorize) ... ok
test_constraint_gen (gpkit.tests.t_nomials.TestPosynomial)
Test creation of Constraints via operator overloading ... ok
test_diff (gpkit.tests.t_nomials.TestPosynomial)
Test differentiation (!!) ... ok
test_eq (gpkit.tests.t_nomials.TestPosynomial)
Test Posynomial __eq__ ... ok
test_eq_units (gpkit.tests.t_nomials.TestPosynomial) ... ok
test_init (gpkit.tests.t_nomials.TestPosynomial)
Test Posynomial construction ... ok
test_integer_division (gpkit.tests.t_nomials.TestPosynomial)
Make sure division by integer doesn't use Python integer division ... ok
test_mono_lower_bound (gpkit.tests.t_nomials.TestPosynomial)
Test monomial approximation ... ok
test_posyposy_mult (gpkit.tests.t_nomials.TestPosynomial)
Test multiplication of Posynomial with Posynomial ... ok
test_simplification (gpkit.tests.t_nomials.TestPosynomial)
Make sure like monomial terms get automatically combined ... ok
test_div (gpkit.tests.t_nomials.TestMonomial)
Test Monomial division ... ok
test_eq_ne (gpkit.tests.t_nomials.TestMonomial)
Test equality and inequality comparators ... ok
test_init (gpkit.tests.t_nomials.TestMonomial)
Test multiple ways to create a Monomial ... ok
test_latex (gpkit.tests.t_nomials.TestMonomial)
Test latex string creation ... ok
test_mul (gpkit.tests.t_nomials.TestMonomial)
Test monomial multiplication ... ok
test_numerical_precision (gpkit.tests.t_nomials.TestMonomial)
not sure what to test here, placeholder for now ... ok
test_pow (gpkit.tests.t_nomials.TestMonomial)
Test Monomial exponentiation ... ok
test_repr (gpkit.tests.t_nomials.TestMonomial)
Simple tests for __repr__, which prints more than str ... ok
test_str_with_units (gpkit.tests.t_nomials.TestMonomial)
Make sure __str__() works when units are involved ... ok
test_units (gpkit.tests.t_nomials.TestMonomial)
make sure multiplication with units works (issue 492) ... ok
test_eq_ne (gpkit.tests.t_nomials.TestSignomial)
Test Signomial equality and inequality operators ... ok
test_init (gpkit.tests.t_nomials.TestSignomial)
Test Signomial construction ... ok
test_additive_scalar (gpkit.tests.t_constraints.TestConstraint)
Make sure additive scalars simplify properly ... ok
test_additive_scalar_gt1 (gpkit.tests.t_constraints.TestConstraint)
1 can't be greater than (1 + something positive) ... ok
test_bad_elements (gpkit.tests.t_constraints.TestConstraint) ... ok
test_constraintget (gpkit.tests.t_constraints.TestConstraint) ... ok
test_equality_relaxation (gpkit.tests.t_constraints.TestConstraint) ... ok
test_evalfn (gpkit.tests.t_constraints.TestConstraint) ... ok
test_init (gpkit.tests.t_constraints.TestConstraint)
Test Constraint __init__ ... ok
test_oper_overload (gpkit.tests.t_constraints.TestConstraint)
Test Constraint initialization by operator overloading ... ok
test_inheritance (gpkit.tests.t_constraints.TestMonomialEquality)
Make sure MonomialEquality inherits from the right things ... ok
test_init (gpkit.tests.t_constraints.TestMonomialEquality)
Test initialization via both operator overloading and __init__ ... ok
test_non_monomial (gpkit.tests.t_constraints.TestMonomialEquality)
Try to initialize a MonomialEquality with non-monomial args ... ok
test_str (gpkit.tests.t_constraints.TestMonomialEquality)
Test that MonomialEquality.__str__ returns a string ... ok
test_init (gpkit.tests.t_constraints.TestSignomialInequality)
Test initialization and types ... ok
test_posyslt1 (gpkit.tests.t_constraints.TestSignomialInequality) ... ok
test_posyconstr_in_gp (gpkit.tests.t_constraints.TestTight)
Tests tight constraint set with solve() ... ok
test_posyconstr_in_sp (gpkit.tests.t_constraints.TestTight) ... ok
test_sigconstr_in_sp (gpkit.tests.t_constraints.TestTight)
Tests tight constraint set with localsolve() ... ok
test_substitution_issue905 (gpkit.tests.t_constraints.TestBounded) ... ok
test_array_mult (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_constraint_gen (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_elementwise_mult (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_empty (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_getitem (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_left_right (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_ndim (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_outer (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_prod (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_shape (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_substition (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_sum (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_units (gpkit.tests.t_nomial_array.TestNomialArray) ... ok
test_cvxopt_kwargs (gpkit.tests.t_model.TestModelSolverSpecific) ... ok
test_modelname_added (gpkit.tests.t_model.TestModelNoSolve) ... ok
test_no_naming_on_var_access (gpkit.tests.t_model.TestModelNoSolve) ... ok
test_601 (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_additive_constants (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_constants_in_objective_1 (gpkit.tests.t_model.TestGP_mosek_cli)
Issue 296 ... ok
test_constants_in_objective_2 (gpkit.tests.t_model.TestGP_mosek_cli)
Issue 296 ... ok
test_cost_freeing (gpkit.tests.t_model.TestGP_mosek_cli)
Test freeing a variable that's in the cost. ... ok
test_exps_is_tuple (gpkit.tests.t_model.TestGP_mosek_cli)
issue 407 ... ok
test_mdd_example (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_posy_simplification (gpkit.tests.t_model.TestGP_mosek_cli)
issue 525 ... ok
test_sensitivities (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_sigeq (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_simple_united_gp (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_singular (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_terminating_constant_ (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_trivial_gp (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_trivial_vector_gp (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_zero_lower_unbounded (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_zeroing (gpkit.tests.t_model.TestGP_mosek_cli) ... ok
test_601 (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_additive_constants (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_constants_in_objective_1 (gpkit.tests.t_model.TestGP_cvxopt)
Issue 296 ... ok
test_constants_in_objective_2 (gpkit.tests.t_model.TestGP_cvxopt)
Issue 296 ... ok
test_cost_freeing (gpkit.tests.t_model.TestGP_cvxopt)
Test freeing a variable that's in the cost. ... ok
test_exps_is_tuple (gpkit.tests.t_model.TestGP_cvxopt)
issue 407 ... ok
test_mdd_example (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_posy_simplification (gpkit.tests.t_model.TestGP_cvxopt)
issue 525 ... ok
test_sensitivities (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_sigeq (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_simple_united_gp (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_singular (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_terminating_constant_ (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_trivial_gp (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_trivial_vector_gp (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_zero_lower_unbounded (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_zeroing (gpkit.tests.t_model.TestGP_cvxopt) ... ok
test_initially_infeasible (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_issue180 (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_partial_sub_signomial (gpkit.tests.t_model.TestSP_mosek_cli)
Test SP partial x0 initialization ... ok
test_relaxation (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_sigs_not_allowed_in_cost (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_small_named_signomial (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_sp_bounded (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_sp_initial_guess_sub (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_sp_substitutions (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_trivial_sp (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_trivial_sp2 (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_unbounded_debugging (gpkit.tests.t_model.TestSP_mosek_cli)
Test nearly-dual-feasible problems ... ok
test_values_vs_subs (gpkit.tests.t_model.TestSP_mosek_cli) ... ok
test_initially_infeasible (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_issue180 (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_partial_sub_signomial (gpkit.tests.t_model.TestSP_cvxopt)
Test SP partial x0 initialization ... ok
test_relaxation (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_sigs_not_allowed_in_cost (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_small_named_signomial (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_sp_bounded (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_sp_initial_guess_sub (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_sp_substitutions (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_trivial_sp (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_trivial_sp2 (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_unbounded_debugging (gpkit.tests.t_model.TestSP_cvxopt)
Test nearly-dual-feasible problems ... ok
test_values_vs_subs (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_call (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_call_units (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_call_vector (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_key_options (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_subinto (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_table (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_units_sub (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_nan_printing (gpkit.tests.t_solution_array.TestResultsTable)
Test that solution prints when it contains nans ... ok
test_result_access (gpkit.tests.t_solution_array.TestResultsTable) ... ok
test_init (gpkit.tests.t_small.TestHashVector)
Make sure HashVector acts like a dict ... ok
test_mul_add (gpkit.tests.t_small.TestHashVector)
Test multiplication and addition ... ok
test_neg (gpkit.tests.t_small.TestHashVector)
Test negation ... ok
test_pow (gpkit.tests.t_small.TestHashVector)
Test exponentiation ... ok
test_shape (gpkit.tests.t_small.TestCootMatrix) ... ok
test_pint_366 (gpkit.tests.t_small.TestSmallScripts) ... ok
test_unitstr (gpkit.tests.t_small.TestSmallScripts) ... ok
test_autosweep_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_autosweep_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_beam_cvxopt (gpkit.tests.t_examples.TestExamples) ... C:\Users\thalheimer.william\AppData\Local\Continuum\Anaconda2\lib\site-packages\gpkit\gpkit\nomials\data.py:186: RuntimeWarning: invalid value encountered in double_scalars
  mmap[i][j] = mag(expmap[exp][j]/c)
ok
test_beam_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_debug_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_debug_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_external_sp2_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_external_sp2_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_external_sp_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_external_sp_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_model_var_access_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_model_var_access_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_performance_modeling_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_performance_modeling_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_primal_infeasible_ex1_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_primal_infeasible_ex1_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_primal_infeasible_ex2_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_primal_infeasible_ex2_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_relaxation_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_relaxation_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_simple_box_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_simple_box_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_simple_sp_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_simple_sp_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_simpleflight_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_simpleflight_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_sin_approx_example_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_sin_approx_example_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_unbounded_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_unbounded_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_vectorize_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_vectorize_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_water_tank_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_water_tank_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_x_greaterthan_1_cvxopt (gpkit.tests.t_examples.TestExamples) ... ok
test_x_greaterthan_1_mosek_cli (gpkit.tests.t_examples.TestExamples) ... ok
test_dictlike (gpkit.tests.t_keydict.TestKeyDict) ... ok
test_failed_getattr (gpkit.tests.t_keydict.TestKeyDict) ... ok
test_getattr (gpkit.tests.t_keydict.TestKeyDict) ... ok
test_setattr (gpkit.tests.t_keydict.TestKeyDict) ... ok
test_vector (gpkit.tests.t_keydict.TestKeyDict) ... ok

----------------------------------------------------------------------
Ran 216 tests in 14.972s

OK
........................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 216 tests in 9.479s

OK

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

**Comment by bqpd** [comment]
Let's meet up and debug this some morning!
