### ISSUE TITLE
remove VectorVariable

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1174]
instead, use `with Vectorize`!

(keep `ArrayVariable`)

**Comment by pgkirsch** [comment]
This seems controversial? Is ArrayVariable just like VectorVariable?

**Comment by bqpd** [comment]
Yup, it's exactly the same.

**Comment by bqpd** [comment]
with Vectorize is a nice way to get people comfortable with vectorization, and lets multiple variables be declared at once to have N/N-1 points, which can help with off-by-one errors.
