### ISSUE TITLE
Sum(single element vector) not working. 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1178]
This is an issue in SPaircraft, in commit  4fcfe72 of branch multimissionFix. 
I define the following variable ```W_{f_{missions}}``` in aircraft.py, which is the objective. It is a non vectorized variable, which is lower bounded by the sum of the values of the vectorized variable ```W_{f_{total}}```:
```python
        ## ---------------------- MULTIMISSION SETUP --------------------------
        W_fmissions = Variable('W_{f_{missions}}', 'lbf', 'Fuel burn across all missions')
        constraints.extend([
                  W_fmissions >= sum(aircraft['W_{f_{total}}']),
                  ])
```
When I run the multimission solve below:
```python
run SP_aircraft
sol = run_optimal_D8('W_{f_{missions}}', False, True)
```
It works fine. But when I run the single mission solve with a single element vector for W_{f_{total}}:
```python
run SP_aircraft
sol = run_optimal_737('W_{f_{missions}}', False, True)
```
I get the following KeyError:
```python
Traceback (most recent call last):
  File "C:\Users\Berk\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-068a99a1d10e>", line 1, in <module>
    sol = run_optimal_737('W_{f_{missions}}', True, False)
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\SPaircraft\SP_aircraft.py", line 344, in run_optimal_737
    m = Mission(Nclimb, Ncruise, objective, aircraft, Nmission)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\model.py", line 59, in __init__
    cs = self.setup(*args, **kwargs)  # pylint: disable=no-member
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\SPaircraft\aircraft.py", line 1226, in setup
    self.cost = aircraft[objective]
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\set.py", line 55, in __getitem__
    return self._choosevar(key, self.variables_byname(key))
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\set.py", line 59, in _choosevar
    raise KeyError(key)
KeyError: 'W_{f_{missions}}'
```
Kind of odd. It's like the variable doesn't exist at all?

**Comment by bqpd** [comment]
Ohhh. Use `.sum()`, not `sum()`

**Comment by bqpd** [comment]
The KeyError might be caused by that constraint not including the `'W_{f_{missions}}'` because sum() is returning something blank.

**Comment by bqpd** [comment]
I can't reproduce this error; on that branch I just get a DUAL_INFEASIBLE solve, no KeyError with either

**Comment by bqpd** [comment]
I'm getting DUAL_INFEASIBILITY for the first command above?

**Comment by bqpd** [comment]
Nope, that doesn't fix it.

**Comment by bqpd** [comment]
This isn't an error with `sum`, anyway: the problem is that on line 1226 of `aircraft.py` (`self.cost = aircraft[objective]`) you assume non-standard objective will in in `aircraft`, but 'W_{f_{missions}}' is in fact defined in `Mission`
