### ISSUE TITLE
Allowing topvar function for substitutions

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1185]
I would like to do this: 
```python
self.wing.substitutions.topvar("m_{fac}") = 1.1
```
inside my solar model.  Is this possible to do?

**Comment by mjburton11** [comment]
I can do this, which is pretty clean.  So... maybe not necessary to do the above
```python self.wing.substitutions[self.wing.topvar("m_{fac}")] = 1.1`

**Comment by bqpd** [comment]
Yeah, that's the preferred method...
