### ISSUE TITLE
Slow build time for matrix VectorVariables

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1186]
Using matrices in VectorVariables for wing vortex lattice method took a very long time to build.  Actual solve time was very fast.  See convexengineering/gplibrary@1b0c5559ca643bdc7fccab9e041fc636794745a3

**Comment by bqpd** [comment]
https://github.com/convexengineering/gpkit/pull/1196 takes the solve time on my computer from 112 seconds to 5.4 seconds....it's still much more than if these constants are just treated as numbers, but at least you get 150 extra sensitivities?

**Comment by mjburton11** [comment]
Haha, that's cool.
