### ISSUE TITLE
Mosek 8 installation errors

### ISSUE THREAD

**Issue by courtin** [convexengineering/gpkit#1195]
I'm having trouble getting gpkit to work with mosek 8 on OSX; the tests that come with mosek all pass, as do the tests in the installation instructions.  I've attached the results of gpkit.tests.run() below
[gpkit_errors.txt](https://github.com/convexengineering/gpkit/files/1434545/gpkit_errors.txt)

**Comment by bqpd** [comment]
The Mac linking bug. Are you free to meet this week to debug this? For now
mosek_cli should work

**Comment by courtin** [comment]
Thanks! Yea,  I'm free anytime today after 4 or tomorrow except between 2-3.
