### ISSUE TITLE
unable to vectorize models with vector variables

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1200]
I don't know if anyone else has had this problem, but I can't seem to vectorize models with vector variables.  I tried the following on convexengineering/ondemand@77bc3b21f1fc6424e3aa7c49e9247026785fc78d:

```python
In [1]: from stol import Mission

In [2]: from gpkit import Vectorize

In [3]: with Vectorize(3):
   ...:     mm = Mission()

/Users/mjburton11/anaconda/lib/python2.7/site-packages/numpy/core/numeric.pyc in full(shape, fill_value, dtype, order)
    301         dtype = array(fill_value).dtype
    302     a = empty(shape, dtype, order)
--> 303     multiarray.copyto(a, fill_value, casting='unsafe')
    304     return a
    305 

ValueError: could not broadcast input array from shape (5) into shape (5,3)
```

**Comment by bqpd** [comment]
hmm, I think this might have something to do with substitutions, because that's totally supposed to be broadcastable

**Comment by bqpd** [comment]
where's the `takeoff` model from? I can't run this :(

**Comment by bqpd** [comment]
ah great it's in master.

**Comment by bqpd** [comment]
I don't get this bug, so it's probably another new numpy thing? But I do get some other bugs when you try to substitute 0.5 for `\lambda_Mission/Aircraft/Wing/Planform` that could use a better error message...or should we allow scalar substitutions for vectors?

**Comment by bqpd** [comment]
Ah wait derp I found it. I was on an old commit of gplibrary
