### ISSUE TITLE
new warning for signomial in non-signomial enabled enviornment?

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#1202]
Just curious why the error for having a signomial constraint in a non-signomial environment is 

```TypeError: unsupported operand type(s) for -: 'Variable' and 'Variable'```

I thought I remembered the error being something different and more informative...

**Comment by bqpd** [comment]
it's better when you have a invalid constraint, like `x + y >= 1`

**Comment by bqpd** [comment]
We don't overload subtraction when not in a SignomialsEnabled environment so as to allow other libraries etc to define their own interactions with -...we could overload it all the time though, to improve the error message

**Comment by mayork** [comment]
okay gotcha, I was thinking of the error given for constraints like `x + y >= 1`.

I think the error message would improve with operator overloading but I'm not sure it's worth overloading - just for an error message.
