### ISSUE TITLE
can't delete substitutions within model

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1232]
I'm trying to the following in `solar`

```python
  class Aircraft(Model):
      "vehicle"
      fuseModel = None
      def setup(self, sp=False):
  
          self.wing = WingGP()
          del self.wing.substitutions["\\tau"]
```
 but it won't delete the substitution.   If I delete it after creating mission, it will delete.  Is this behavior intended?

**Comment by bqpd** [comment]
Oh dang I bet this is related to #1175...

**Comment by bqpd** [comment]
Yeah, it's something that occurs in performance models, which pull the substitutions back out of the value; then when the mission combines them, the `\\tau` substitution has magically reappeared

**Comment by bqpd** [comment]
Hmm you know what...both this and #1175 would be fixed if values were removed from a variable after being used...that could be kinda odd though
