### ISSUE TITLE
parsing_vars cant find self declared variables for function calls

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1234]
In `wing_test.py` on convexengineering/gplibrary@c1b7c9b94e585d9595687434c867f3c40ff6b415 it can't find the variable `self.eta` in an evaluated fixed variable function.

**Comment by bqpd** [comment]
the problem is still the spaces in `np.linspace(0, 1, 5)`; replace with `np.linspace(0,1,5) `

**Comment by mjburton11** [comment]
derp... I remember you telling me this now.  Sorry
