### ISSUE TITLE
SP sankey diagrams

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1242]
I was hoping to plot the feasibility sets of SimPleAC, but I can't. Would appreciate having this fixed ASAP.

**Comment by 1ozturkbe** [comment]
for clarification, m.program.gps[number].varkeys is an empty set.

**Comment by bqpd** [comment]
try with `mutategp=False` to build the full GP each time? or use `.varlocs`. If this is specifically an issue with feasibility plots it should be raised in https://github.com/convexengineering/robust

**Comment by 1ozturkbe** [comment]
No,  doesn't resolve the issue. I want to be able to get the variables from within the GP. But I can't get them with either of these notations (which do the same thing, other than the fact that variables_byname returns an array of variables vs m[-] which returns a variable object:
```python
m[varkey]
m.variables_byname(varkey)
```
They both return ```None```.  The error message is below
```python 
In [14]: plot_feasibilities(a.variables_byname('C_{L,max}'),a.variables_byname('V_{min}'),a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-012705eb14fd> in <module>()
----> 1 plot_feasibilities(a.variables_byname('C_{L,max}'),a.variables_byname('V_{min}'),a)

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\set.pyc in variables_byname(self, key)
     94         from ..nomials import Variable
     95         variables = [Variable(newvariable=False, **key.descr)
---> 96                      for key in self.varkeys[key]]
     97         variables.sort(key=_sort_by_name_and_idx)
     98         return variables

TypeError: 'NoneType' object has no attribute '__getitem__'
```
The error is not in plot_feasibilities. It is within the GP approximations from which I can't reference variables?

**Comment by 1ozturkbe** [comment]
It turns out that the same issue affects the Sankey diagram generation for the last GP in an SP solve.

**Comment by bqpd** [comment]
clearly I should start testing these things with SPs :p

(Sankey is going to need mutategp=False to maintain the model structure
that makes the sankey diagrams fun...)

**Comment by 1ozturkbe** [comment]
Could we address this issue soon? I would like to be able to use feasibility sets in my thesis, and this is a weird bug that makes it very inconvenient if not impossible.

**Comment by bqpd** [comment]
Next on the plate after I get Sankey merged with SPs working!

**Comment by 1ozturkbe** [comment]
sweeeet

**Comment by 1ozturkbe** [comment]
@bqpd lmk when you make headway with this. No pressure, I know you are taking some time off.

**Comment by bqpd** [comment]
This works! On solar, none of the sensitivities change interestingly over the solves...this was the best I could find between the first and last GP.

![image](https://user-images.githubusercontent.com/1482776/37737013-c72cae1e-2d0f-11e8-861d-c8bb7538b643.png)

![image](https://user-images.githubusercontent.com/1482776/37737031-d41f02b6-2d0f-11e8-9748-f7d5b1817c9b.png)
