### ISSUE TITLE
Move .interactive to new repository

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1244]
As part of this
  - consider what to do with controlpanel per https://github.com/convexengineering/gpkit/issues/508
  - stop supporting sensitivity map

**Comment by bqpd** [comment]
stop supporting sensitivity map

**Comment by 1ozturkbe** [comment]
@bqpd I agree that interactive should become its separate repo. I have never used sensitivity map in the past; is that the ranked bar chart of the sensitivities? I think that is somewhat useful, although if we revive that I think we need to figure out what to do about vector constants (I vote we 'aggregate' the sensitivity by summing it all up).

**Comment by bqpd** [comment]
naw sensitivity map colors the raw sensitivity output.
