### ISSUE TITLE
Calling units of dimensionless variable should not throw error

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1252]
This is relatively straightforward. Currently, if we have a dimensionless variable like aspect ratio, calling
```python
sol('AR').magnitude
```
throws an error
```python
AttributeError: 'numpy.float64' object has no attribute 'magnitude'
```
In the solution dicts, we should have uniformity so that we can call magnitude on all of them without issues.

**Comment by bqpd** [comment]
the solution for this right now is the `mag` function in `gpkit.small_scripts` (e.g. `mag(sol('AR'))`)...another alternative would be to make all dimensionless quantities Pint Quantity objects.

**Comment by 1ozturkbe** [comment]
I did see that function later, but to me that is a hack. And I think that magnitude should definitely be an attribute just like .units etc. Feel free to disagree.

**Comment by mjburton11** [comment]
I agree with @1ozturkbe on this one.  For usability, this would be really nice to have.  Is there any concern that a user would think that if `magnitude` is an attribute then it must not be dimensionless?

**Comment by 1ozturkbe** [comment]
It seems like magnitude as a function should be agnostic to whether or not something has units. Also another issue is that calling ```m[varname].units``` where the variable has no units throws an error as well. These issues are coupled.

**Comment by bqpd** [comment]
Naw this is just a minor speed optimization; I'll take it out and make all sol arrays into Quantities
