### ISSUE TITLE
not installing on latest version of anaconda

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1253]
Ok I just tried installing gpkit on someone else's computer after just downloading the latest version of anaconda and it threw a bunch of errors on installation.  Not the latest version but clone what's one master.  Any idea as to what is going on?

**Comment by bqpd** [comment]
nope! what OS? any chance you can copy/paste the error messages?

**Comment by mjburton11** [comment]
OS 10.9 I believe.  And no I should have... but it was a Syntax Error on line 126 of `bounded.py`???

**Comment by bqpd** [comment]
?weird?

**Comment by mjburton11** [comment]
very weird.  I was so confused.

**Comment by nillst** [comment]
Talking to  @mjburton11 . Replicated the bug (see code below). After installing conda, gpkit tries to install with python3.

```python
root@condaTest:~/gpkit# pip install .
Processing /root/gpkit
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-dqdyybje-build/setup.py", line 8, in <module>
        from gpkit.build import build_gpkit
      File "/tmp/pip-dqdyybje-build/gpkit/__init__.py", line 20, in <module>
        from .tools.docstring import parse_variables, verify_model
      File "/tmp/pip-dqdyybje-build/gpkit/tools/docstring.py", line 3, in <module>
        from ..constraints.bounded import Bounded
      File "/tmp/pip-dqdyybje-build/gpkit/constraints/bounded.py", line 126
        print "Solves with these variables bounded:"
                                                   ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Solves with these variables boundd:")?
    Could not load settings file.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-dqdyybje-build/
```

**Comment by nillst** [comment]
Using "pip install gpkit" installs successfully.

**Comment by mjburton11** [comment]
Ok @nillst correct me if I'm wrong but I think we identified the python version being the issue.  Works on 2.7 but not 3.6 correct? 

We should probably have a better error message for this

**Comment by nillst** [comment]
Correct, gpkit must be installed with python2 at this point. (See isue #1039)

**Comment by nillst** [comment]
Correct, gpkit must be installed with python2 at this point. (See issue #1039)
