### ISSUE TITLE
alternative install location for mosek

### ISSUE THREAD

**Issue by andrewning** [convexengineering/gpkit#1254]
/private/var/folders/r0/5bhjqvqj3b17jr0m8n6lwpsm0000gn/T/pip-build-UydGZI/gpkit/

Not a big deal, but it might be nice to allow mosek to be installed somewhere other than $HOME, maybe through a command line arg or environment variable.  mosek v8 doesn't assume installation in $HOME like some past versions did. Just a personal preference - I like to keep these types of programs in a separate folder to not clutter my home directory - but like I said not a big deal.

Perhaps that would also allow for mosek to be installed through conda, for those that to go that route.

**Comment by bqpd** [comment]
@andrewning, #1273 looks for an `MSKHOME` environment variable, and uses that as the MOSEK path. This seemed the most MOSEK-y thing to do, but does it work for your purpose?
