### ISSUE TITLE
version on master does not enforce pint requirement

### ISSUE THREAD

**Issue by nillst** [convexengineering/gpkit#1255]
The version of GPkit currently on master does not check that pint is installed. This has been causing some installation errors for some users. 
`pip install gpkit`
will check for pint and automatically install if not already satisfied.

**Comment by bqpd** [comment]
Huh, it should be raising an ImportError in pint/__init__.py if pint is not
installed. What do you mean by "check that pint is installed"; should we
raise a more helpful error message?

**Comment by nillst** [comment]
Is there a way to have pip check for the dependencies and download missing packages rather than having the gpkit installation throw the error?

**Comment by bqpd** [comment]
It should! that's the whole point of the install_requires section in setup.py, and I've seen it doing so before.

**Comment by nillst** [comment]
This makes sense. 
I will try to recreate the issue where pip doesn't catch it before the gpkit install fails.

**Comment by bqpd** [comment]
Closing this for now...
