### ISSUE TITLE
CVX algorithm parameters- how to modify?

### ISSUE THREAD

**Issue by Alex-Vidal** [convexengineering/gpkit#1256]
Hello,
I am interested in running a GP model via cvxopt. However, I can't find how to set some parameters for the solver (tolerances, max_iters). I wanted to know if modifying these options is supported and how would one go around to set them (since I don't seem to find an obvious way). Is it via the Model .solve kwargs?
Thank you all for your continued contributions to this project. :-)

**Comment by bqpd** [comment]
yup! Model.solve kwargs will be passed on to cvxopt's gpsolver :) Where do you think would be the right place to document this?

**Comment by Alex-Vidal** [comment]
And how would you go about sending the options? Because when I try something like this, it is certainly not stoping after two iterations:

my_options = {'maxiters': 2, 'show_progress': False}
sol = m.solve(verbosity=2, kwargs=my_options)

Probably an example with the adequate syntax would be fine somewhere around "Advanced commands" in the doc.
Thanks!

**Comment by bqpd** [comment]
oh, you'll want either

````python
my_options = {'maxiters': 2, 'show_progress': False}
sol = m.solve(verbosity=2, **my_options)
```

or

```python
sol = m.solve(verbosity=2, maxiters=2, show_progress=False)
````

**Comment by Alex-Vidal** [comment]
Something is amiss. Using the latter, the one line solution, still the search goes beyond iteration 2:

Using solver 'cvxopt'
Solving for 15 variables.
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00  5.2338e+00  3e+01  1e+00  1e+00
 1:  4.1821e+00 -5.9314e-01  1e+01  3e-01  3e-01
 2:  5.2398e+00  3.0676e+00  2e+00  2e-02  2e-02
 3:  4.2314e+00  3.8608e+00  4e-01  3e-03  3e-03
 4:  4.0133e+00  3.9444e+00  8e-02  1e-03  5e-04
 5:  3.9752e+00  3.9625e+00  2e-02  4e-04  2e-04
 6:  3.9709e+00  3.9691e+00  2e-03  5e-05  2e-05
 7:  3.9703e+00  3.9703e+00  7e-05  2e-06  8e-07
 8:  3.9703e+00  3.9703e+00  7e-07  2e-08  8e-09
Optimal solution found.
Solving took 0.0242 seconds.
result packing took 86% of solve time
solution checking took 4.6% of solve time

**Comment by bqpd** [comment]
Ah, sorry, you'll want

```python
sol = m.solve("cvxopt", verbosity=4, options={"maxiters": 2})
```

as shown in http://cvxopt.org/userguide/solvers.html#algorithm-parameters

**Comment by Alex-Vidal** [comment]
Now, that is working. Thank you very much for you help. :-)
