### ISSUE TITLE
Best solution up to some point

### ISSUE THREAD

**Issue by Alex-Vidal** [convexengineering/gpkit#1257]
Hello again =)
I am using GP to tackle a fairly large problem to which I don't need the exact optimum; a close enough solution would be good already. My though was achieving this by limiting the number of iterations and reading the best solution up to the point. However when reaching maxiters, I understand I should access cvxopt's model.program.solver_out, but can't see how to do it and the program gets killed right away. What would be the way to do so?

Maybe running the problem with higher tolerances would be of any use, instead of limiting the number of iterations?

**Comment by bqpd** [comment]
Yeah, for that use case I think you'd be better off changing the tolerances!

For what you described, though, you just have to wrap the solve call in a try/except so that you can pull the solver_out data out after catching gpkit's complaint that the solution is not optimal.

**Comment by Alex-Vidal** [comment]
So if I were to use the try/except method, how should the solver_out data be accessed? I am doing something like this,

m = Model(objective, constraints)
try:
    sol = m.solve("cvxopt", verbosity=2, options={'maxiters':2})
except:
	prog = m.gp()
	result_dict = prog._compile_result(prog.solver_out)
	print result_dict

However, prog.solver_out seems to be None and thus when doing _compile_result I get the following,

Traceback (most recent call last):
  File "instance.py", line 2684, in <module>
    result_dict = m.gp()._compile_result(m.gp().solver_out)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/gp.py", line 275, in _compile_result
    primal = solver_out["primal"]

Maybe you could point out to what would be missing in this case?

**Comment by Alex-Vidal** [comment]
In the case of lowering tolerances (reltol and feastol in this case), I also get a warning and must use a try/except, resulting in the same situation where I'm unable to recover the result from solver_out.

```
Traceback (most recent call last):
  File "big_instance.py", line 8989, in <module>
    sol = m.solve("cvxopt", verbosity=2, options={'reltol':1e-3, 'feastol':1e-3})
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/prog_factories.py", line 82, in solvefn
    result = solvefn(solver, verbosity, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/gp.py", line 223, in solve
    raise e
RuntimeWarning: Dual cost 5311244.623411882 does not match primal cost 5371622.54738566
```

**Comment by avidal12** [comment]
OK, managed to recover the solutions with the following code:
```
m = Model(objective, constraints)
try:
    sol = m.solve("cvxopt", verbosity=0, options={'maxiters':2})
except:
	result = m.program.solver_out
	m.program._generate_nula(result)
	result_dict = m.program._compile_result(result)
```
Notice I had to add the call to generate_nula because otherwise, when limiting the number of iterations, the following error arises:

```
Traceback (most recent call last):
  File "instance3.py", line 2679, in <module>
    result_dict = m.program._compile_result(result)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/gp.py", line 276, in _compile_result
    nu, la = solver_out["nu"], solver_out["la"]
KeyError: 'nu'
```
Which I don't understand because, looking at the code, _compile_result does call _generate_nula on the solver_out at line 274. =/
I have not been able to reproduce the issue when changing tolerance settings.
