### ISSUE TITLE
Initial solution / incremental solving

### ISSUE THREAD

**Issue by avidal12** [convexengineering/gpkit#1260]
I was wondering if there is some way to tell the solver initial values for some variables. I am solving several instances of a problem that could be considered incremental, thus the solution for problem _i_ is considerably close to that of _i+1_ (compared to searching the whole space again).

**Comment by bqpd** [comment]
This is sometimes called a "warm start", and is unfortunately not presently an option for cvxopt or mosek. :( It might be coming with MOSEK 9.
