### ISSUE TITLE
Bound verification not working correctly

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1286]
@bqpd I'm on the latest gpkit version, branch `prop` in `gpkitmodels`, and `prop_integration` in `solar`.  Trying to run `solar.py` I get the following error: 

```python
ValueError: while verifying BoxSpar:
  g has no lower bound
  rho_CFRPFabric has no lower bound
  tmin_CFRPFabric has no lower bound
  rho_FoamHD has no lower bound
  rho_CFRPUD has no lower bound
  tmin_CFRPUD has no lower bound

To fix this add the following to BoxSpar's docstring (you may not need it all): 

Lower Unbounded
---------------
tmin, rho, g
```
I added those variable to `Lower Unbounded` and then got this error: 

```python
AttributeError: `tmin` is noted in BoxSpar as unbounded, but is not an attribute of that model.
```

**Comment by bqpd** [comment]
Worked fine for me after I added a missing `__init__.py` to the `prop` branch of `gplibrary`. Not sure what state your repos were in that you didn't get an import error without that `__init__.py`... but try it now?
