### ISSUE TITLE
mosek vs mosek_cli

### ISSUE THREAD

**Issue by michK** [convexengineering/gpkit#1297]
I am having trouble installing `mosek`, but `mosek_cli` works.

Are these the same solvers or is there an advantage to using `mosek` if `mosek_cli` works?

Thanks.

(Sorry to open this as an issue on github, but not sure where else to ask the question.)

**Comment by bqpd** [comment]
@michK no worries, this is a fine place to ask! What OS are you on? (I'm guessing Windows...)

`mosek` is mostly interchangeable with `mosek_cli`, but `mosek` does have some advantages: it's a little faster to load (useful for small problems), and it can handle more marginally solvable problems (especially those with exponents very near 0, which can occur with some SPs).

**Comment by michK** [comment]
OK, thank you very much.

I am actually on Linux, Ubuntu 14.04.

I think the problem relates to the fact that when I run `python2 -c "from gpkit.build import rebuild; rebuild()"`, some of the output I get is: `ModuleNotFoundError: No module named 'ctypesgencore'`, but when I run `python` and then `import ctypesgencore` it works and I get no error.

I suspect the problem might be related to the fact that I'm using python 2 for gpkit but python 3 is the default system python.

I'm pretty sure that I installed mosek correctly.

Any ideas?

**Comment by bqpd** [comment]
That sounds like it might be the issue... If you run `python2 -c "import ctypesgencore"` do you get the error? Alternately, can you run the python2 version of pip to install ctypesgen?

**Comment by michK** [comment]
Running `python2 -c "import ctypesgencore"`doesn't give an error.

So I just renamed my anaconda3 directory so that the python3 isn't in the path and ran `python2 -c "from gpkit.build import rebuild; rebuild()"` and it worked, so I'm now able to use mosek. I then renamed anaconda3 to its original and gpkit still working.

Thanks for your help!

**Comment by bqpd** [comment]
Oh dang, I know what the error is; I make a call to `python` in the build script, and it was grabbing the wrong python. Good debugging, and thanks for raising the issue!
