### ISSUE TITLE
cvxopt refinement parameter change broke gplibrary

### ISSUE THREAD

**Issue by galbramc** [convexengineering/gpkit#1308]
https://acdl.mit.edu/csi/job/gplibrary_Push_Models/buildnode=reynolds,optimizer=cvxopt/108/

So it looks like some of the gpkit testing is missing testing the gplibrary...

**Comment by bqpd** [comment]
aieee. I can't reproduce this, but I'll revert that.

**Comment by bqpd** [comment]
@galbramc I can't trigger a retest...jenkins is logging me out every time I click "Build now"  on https://acdl.mit.edu/csi/job/gplibrary_Push_Models/. Could you run it a couple times to check if it's a stable failure?

**Comment by galbramc** [comment]
strange. I triggered the build for you. Is there random numbers involved again? Are you maybe just on a threshold of whether it's a success of failure?

**Comment by bqpd** [comment]
It seems stable...Yeah, I wanted to check if it was on some knife-edge without the refinement, but it seems quite consistent. Might be a cvxopt version thing, but I'll revert anyway.
