### ISSUE TITLE
Boundedness Sankey diagrams

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1322]
@1ozturkbe @mjburton11 @pgkirsch what do y'all think about the idea of drawing a pre-solve sankey diagram to show how a variable is upper-lower bounded (lines would be blue/red and all the same width)? I think it would mostly just be useful as a way to explain how boundedness turns into pressures...but if it doesn't seem like something any of you would actually use then I don't think it's worth implementing...

**Comment by 1ozturkbe** [comment]
Hmm I see the purpose, but I think the diagram itself is not a good way to visualize this. We confuse people enough just by trying to explain Sankey diagrams in the first place, so I don't think these would be helpful.  What I think we need to visualize this is to have some way to express the boundedness of variables at a Model level (which would be something like a model level Sankey diagram as you mentioned), and then actually make a diagram of the 'linking' variables going in between model (eg. showing how the upper unboundedness of a variable is resolved by a constraint in another model). I don't have any concrete ways of visualizing this yet, but I think this would help a lot in collaborative projects.

**Comment by bqpd** [comment]
We've had the spider-web graphs that float around...it just gets so chaotic! Maybe there's a better way to use model hierarchy to structure those.
