### ISSUE TITLE
Coverage reports show many untested lines

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1336]
Realized this from 'fails' of Jenkins tests on certain machines.

**Comment by 1ozturkbe** [comment]
Check out https://acdl.mit.edu/csi/job/gpkit_PullRequest_Unit/2556/buildnode=macys,optimizer=cvxopt/cobertura/

**Comment by 1ozturkbe** [comment]
need to test the following:
- [ ] docs.source.examples - plot_sweep1d
- [ ] gpkit.tools - spdata
- [ ] all of gpkit.interactive

**Comment by 1ozturkbe** [comment]
@bqpd I guess the major chunk of this is gpkit.interactive, since plot_sweep1d is related to plot_sweep. I'm not sure why spdata exists, and whether or not it is useful. Can you help me determine which parts of interactive may be deprecated? Then let's divvy up the items in interactive and determine whether or not to remove spdata.

**Comment by bqpd** [comment]
Sounds like a good plan. There's some other issues open on whether
interactive (or at least the ipython-notebook-specific portions of it)
should be in a separate repository...what's your opinion?

**Comment by whoburg** [comment]
@1ozturkbe Thanks for bringing this up! Super important to keep coverage high.

I like the plan @bqpd is outlining in #1183.
