### ISSUE TITLE
Install: missing Pint dependency

### ISSUE THREAD

**Issue by mvernacc** [convexengineering/gpkit#1343]
I recently installed gpkit and encountered the following error:

```bash
 pip install gpkit
Collecting gpkit
  Downloading https://files.pythonhosted.org/packages/27/6e/a5398e511550de206bcbf379f1c776b9abfb419812bd499e8986dd759659/gpkit-0.7.0.0.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 2.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tq9i6481/gpkit/setup.py", line 8, in <module>
        from gpkit.build import build_gpkit
      File "/tmp/pip-install-tq9i6481/gpkit/gpkit/__init__.py", line 4, in <module>
        from ._pint import units, ureg, DimensionalityError
      File "/tmp/pip-install-tq9i6481/gpkit/gpkit/_pint/__init__.py", line 3, in <module>
        from pint import UnitRegistry, DimensionalityError
    ModuleNotFoundError: No module named 'pint'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-tq9i6481/gpkit/
```
This was easily fixed with

```bash
pip install pint
pip install gpkit
```

But it would be nice if `pint` were automatically installed during setup. `pint` is listed in [gpkit's setup.py](https://github.com/convexengineering/gpkit/blob/master/setup.py#L55), so I'm not sure why it wasn't automatically installed.

I'm running python 3.6.5 on ubuntu 16.04.

**Comment by 1ozturkbe** [comment]
I don't see why it wouldn't install immediately, but I see that you are using python 3, although GPkit only supports Python 2.7... I would recommend using 2.7. 
Ned recently made a PR (#1313) that is related to this, and added some dummy imports in pint's place. @bqpd I defer to you to explain to us plebes why this is the case!

**Comment by mvernacc** [comment]
Ah thanks Berk. From reading #1123 and #1039 I got the impression that python 3 might be supported, but I will switch to 2.7. Maybe there should be a note in the readme or install docs indicating that only 2.7 is supported?

**Comment by mvernacc** [comment]
Things are going smoothly in 2.7 now :)  `gpkit.tests.run()` runs w/o errors

**Comment by bqpd** [comment]
@1ozturkbe the build process in pip is...bad...and so builds gpkit before installing its dependencies. This has a different workaround in the latest master branch, which hasn't yet been pushed up to pypi, so @mvernacc would not have seen this error (but would have seen various python3-related test failures)

**Comment by mvernacc** [comment]
@bqpd yes, that's exactly what happened when I tried installing from master last night.
