### ISSUE TITLE
diff() and almost_equal() give ZeroDivisionError

### ISSUE THREAD

**Issue by michK** [convexengineering/gpkit#1345]
When testing the usage of diff() and almost_equal() to compare different solutions, I find that these methods give division by zero errors when used to compare a solution to itself, e.g:

```
sol.almost_equal(sol)
sol.diff(sol)
```

I expect this is because the solutions are exactly equal and thus you cannot calculate a relative error.

However, I think the expected behavior should rather be statements saying that the solutions are exactly equal within some tolerance.

**Comment by bqpd** [comment]
We actually have a unit test for this, confirming that a solution compared to itself prints out "0% different"...but clearly it's not a good enough test! Could you attach or send me code that generates this error?

**Comment by michK** [comment]
I sent you an email. You can reproduce by running `mission_extension_conventional.py` in arch_test_cases directory.

**Comment by bqpd** [comment]
@michK made pullrequest #1346 to address this
