### ISSUE TITLE
Bounded gives ValueError

### ISSUE THREAD

**Issue by michK** [convexengineering/gpkit#1347]
I have a model consisting of submodels.

I'm getting a duel infeasible solution so want to use Bounded to see if my solutions solve.

Wrapping the full list of constraints I send to the solver with `Bounded()` gives the error:

ValueError: xxx could refer to multiple keys in this substitutions KeyDict. Use `.variables_byname(xxx)` to see all of them.

**Comment by bqpd** [comment]
oh, interesting. could you send me the code that triggers this? for the
meantime try using the exclude keyword to skip affected variables and see
if that solves...

**Comment by michK** [comment]
Just sent it.

Not sure how to use the exclude keyword, checked the source also but couldn't figure it out.

Regards

**Comment by bqpd** [comment]
The issue appears to be not with Bounded, but with substitutions that are created after bounding.

I recommend calling `model.debug()`, or if you want to use Bounded directly, applying it as the last step after fully creating your model
