### ISSUE TITLE
make signomial 'tautological constraint' error a warning

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1358]
It seems like there is a workaround for posynomials, but is there one for signomials? Let me know @bqpd.

**Comment by 1ozturkbe** [comment]
@alisaab tagging you as well, because I ran into this error in water_network.

**Comment by 1ozturkbe** [comment]
@bqpd any ideas?

**Comment by bqpd** [comment]
Are you getting the error on line 667/668? That one is testing strictly for 0, so it shouldn't need a workaround....but you can comment that code out for a bit, or check that posy != 0 before creation (which could be annoying with an array constraint).

**Comment by 1ozturkbe** [comment]
Yes, those are the lines. I hate it when this happens, but I can no longer replicate this error... I changed a couple of lines of code and it disappeared. The issue is that when you get this ValueError the solve stops even though the tautological constraint is clearly feasible. Should this be turned into a warning instead of a ValueError?

**Comment by bqpd** [comment]
hmm quite possibly yeah!

**Comment by 1ozturkbe** [comment]
This is part of the PR #1364 .

**Comment by bqpd** [comment]
nice! this looks good; just add a solve to that test.
