### ISSUE TITLE
Want ability to add/change imported units

### ISSUE THREAD

**Issue by Ltrollinger** [convexengineering/gpkit#1362]
GPkit's init function doesn't allow users to prescribe the enable_units path, and so to make it recognize density in slug/ft^3 I had to add a line to the CPI txt file instead. Can we bring units back as a user-defined setting? @bqpd

**Comment by bqpd** [comment]
You should be able to do `gpkit.ureg.load_definitions(filepath)` to load new units from a file!

**Comment by bqpd** [comment]
@Ltrollinger, I'm closing this thread, but let me know if you want me to add slugs to the base units!

**Comment by whoburg** [comment]
See also: 
https://github.com/hgrecco/pint/issues/511

Pint apparently removed the unit to match the NIST handbook.
