### ISSUE TITLE
Environment path length issue

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1363]
I figured out the reason for the issue. It's due to the following lines in gpkit/_mosek/cli_expopt.py, on line 38.
```python
    if "mosek_bin_dir" in settings:
        os.environ['PATH'] = ":".join([os.environ['PATH'],
                                       settings["mosek_bin_dir"]])
```
This for some reason makes the length of PATH so long that it breaks some of the sweeps I am running for robustSP stuff. I changed it to the following in my version of gpkit.
```python
    if "mosek_bin_dir" in settings:
        os.environ['PATH'] = ":".join([os.environ['PATH']])
```
to avoid the growing PATH length. Do you have insight into this @bqpd ?

**Comment by 1ozturkbe** [comment]
@bqpd bump!

**Comment by bqpd** [comment]
@1ozturkbe, added a PR to address this

**Comment by whoburg** [comment]
Haha amazing failure mode
