### ISSUE TITLE
Subinplace deprecation may be hurting repos other than robust

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1368]
Also, documentation needs to be updated [per this robust issue](https://github.com/convexengineering/robust/issues/20).

**Comment by 1ozturkbe** [comment]
Documentation reference [here](https://gpkit.readthedocs.io/en/latest/advancedcommands.html?highlight=subinplace).

**Comment by bqpd** [comment]
Whoops, will do!
