### ISSUE TITLE
throw warning/error if user sets fixed var to 0

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1370]
I just ran into an issue where I got the following error: 
```python
  File "C:\Users\burton.michael\gpkit\gpkit\nomials\math.py", line 615, in sens_from_dual
    nu_, = nu[i]
IndexError: list index out of range
```
Fixed by changing constant from 0 to 1e-10.  I don't know if this is the desired behavior but this error is confusing and at the very least a warning should pop up if the user tries to set a fixed var to zero.

**Comment by bqpd** [comment]
It doesn't happen with most/all fixed variables, so without an MWE I'm not sure what to look for...

**Comment by bqpd** [comment]
@mjburton11 do you have an MWE?
