### ISSUE TITLE
Problem with mosek when the temp directory contains a dot character

### ISSUE THREAD

**Issue by Behrouz-Babaki** [convexengineering/gpkit#1380]
If the default temp directory contains a dot (`.`) character, using Mosek can be problematic. This error can be reproduced by running this script:

```python
import os
os.environ['TMPDIR'] = '/tmp/a.b.c'
os.mkdir('/tmp/a.b.c')

import gpkit.tests
gpkit.tests.run()
```
*This problem turns out to be critical in computing clusters managed by Sun Grid Engine, where the default temp directory is dynamically created by the task manager, and its name can contain the dot character.*

The root of this problem is in `mskexpopt` binary which is [called](https://github.com/convexengineering/gpkit/blob/d38f5687469b1c361635bb3489410843944e8e54/gpkit/_mosek/cli_expopt.py#L85) by gpkit. The default solution file name that `mskexpopt` generates is obtained by removing everything after the first dot character in the name of the input file, and replacing that with `.sol`. So if the input file is `/tmp/a.b.c/gpkit_mosek`, the solution file will be `/tmp/a.sol`, while gpkit expects it to be `/tmp/a.b.c/gpkit_mosek.sol`. 

The fix is simple, as `mksexpopt` allows the user to specify the name for the solution file. It is enough to replace the [following](https://github.com/convexengineering/gpkit/blob/d38f5687469b1c361635bb3489410843944e8e54/gpkit/_mosek/cli_expopt.py#L85-L87) lines:
```python
        for logline in check_output(["mskexpopt", filename]).split(b"\n"):
            print(logline)
        with open(filename+".sol") as f:
```
with these ones:
```python
        solution_filename = filename + ".sol"
        for logline in check_output(["mskexpopt", filename, 
                                     "-sol", solution_filename]).split(b"\n"):
            print(logline)
        with open(solution_filename) as f:
```

**Comment by bqpd** [comment]
@Behrouz-Babaki thank you for this fix! This is also a major issue in companies using Windows with usernames containing periods.
