### ISSUE TITLE
Discussing post-processing of Tight for complex ArrayConstraints

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1386]
This is mostly to have a debate on the right process for using information about untight constraints. Right now, we post a warning on untight Tight constraints of ```printwarning=True```, but this is somewhat useless if the user needs to be able to use that information for some kind of post-processing (eg. me, for solid rocket motor shape design) or to get some intuition. And also, text is *meh*. Being able to make some visual interface would be nice. 

One proposal was to simply add kwargs to each Tight constraint, but that is super messy, especially if you have an ArrayConstraint. I will be debating this for the next while, so let me know if you have ideas @bqpd and others!

**Comment by bqpd** [comment]
@1ozturkbe, check out the new warnings and constraints-printing in https://github.com/convexengineering/gpkit/pull/1388. (try running a model with Tight constraints then doing `print sol.table(tables=["warnings", "tightest constraints", "loose constraints"])`) and let me know what you think! The warnings table will print by default now, so it's less important to print warnings during a solve.

**Comment by bqpd** [comment]
For your purposes the new format of `sol["warnings"]["Unexpectedly Loose Constraints"]`, where each entry is a tuple of `(warning_message, flagged_constraint)` should help with parsing according to your flags above.

**Comment by bqpd** [comment]
I think this is closed by the above functionality; @1ozturkbe, can you confirm?

**Comment by 1ozturkbe** [comment]
That’s right, thanks for following up on this @bqpd.
