### ISSUE TITLE
Support MOSEK v9

### ISSUE THREAD

**Issue by erling-d-andersen** [convexengineering/gpkit#1396]
Mosek v9 is now released. Does gpkit support with Mosek v9?

If no, then there should be huge advatange using v9 rather than v8. We can potentially help you i.e. create a pull request with v9 support.

**Comment by bqpd** [comment]
I've got a version of mosek9 support that I'll be putting up soon; would love to get your feedback on the best way to do warm starts, etc. once that's in a reviewable state!

**Comment by erling-d-andersen** [comment]
There is no way of doing warmstarts.

**Comment by erling-d-andersen** [comment]
How do you call Mosek? Via Fusion or via the optimizer API?

**Comment by erling-d-andersen** [comment]
Warmstarts is only available when you are using the simplex optimizers and you do not.

I would think the optimizer API is the right the choice. But we can take a look at your Fusion implementation if you like.

**Comment by erling-d-andersen** [comment]
You can reopen if you need help.

**Comment by whoburg** [comment]
@bqpd, I'm assuming this is still in work. Thinking we should leave the issue open until v9 is supported.

**Comment by rileyjmurray** [comment]
@1ozturkbe if you'd like, I can help with this. The main reason I haven't been in touch (re: SAGE + GPKit), is that GPKit doesn't yet support MOSEK 9.

**Comment by 1ozturkbe** [comment]
Riley, that would be amazing!! I am also thinking of adding mixed integer capability to GPkit that would require Mosek 9, so it'd be great to have some help! (To be honest I have no idea what this even requires.)

**Comment by rileyjmurray** [comment]
Sounds good; I'm happy to give it a shot! I expect this will take a fair amount of coordination though. At some point we should have a phone call, but I can start by getting to know the master branch a bit. 

As a preliminary question: are there any planned changes to the master branch, which might affect the input a solver interface needs to handle?

**Comment by 1ozturkbe** [comment]
In the near future, the only difference will be the ability to support integer variables (added in Mosek9), where we would like to provide Mosek with the set of possible integer values that it could take. (I have been looking at the MICO example [here](https://docs.mosek.com/9.0/pythonapi/tutorial-mio-shared.html) but have mostly focused on being able to pass the integer sets through the GPkit objects rn.)

We should definitely have a call as soon as possible to coordinate. My schedule is busy but flexible until Thursday next week.

**Comment by rileyjmurray** [comment]
Sorry for not responding earlier. It looks like a basic implementation will be easier than I thought; I should have such an implementation ready for testing by tomorrow. We can coordinate by text for a phone call, once I've seen how the implementation fares with the usual test suite.

**Comment by 1ozturkbe** [comment]
Wow you are a boss @rileyjmurray, looking forward to it! I will be traveling this weekend through next weekend but I will be working at a limited bandwidth and should definitely have time for a call!

**Comment by rileyjmurray** [comment]
@bqpd @1ozturkbe Okay I have an implementation ready to go. It hits all the notes from #1374 , except it uses the "Optimizer" interface instead of the "Fusion" interface. The difference is that the Optimizer interface is considered more stable, and is faster than the Fusion interface.

All solver related tests are passing. I'll make the PR once I improve the in-line comments explaining how it works. I'll highlight natural remaining work (e.g. handling user-provided MOSEK solver parameters, or the work necessary to allow mixed-integer GP) in the PR.
