### ISSUE TITLE
Installation with pip errors

### ISSUE THREAD

**Issue by kjgoodrick** [convexengineering/gpkit#1398]
Hello,

I am currently trying to install gpkit with pip and I have run into a few errors during the installation process:

1.  
```` 
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<user>\AppData\Local\Temp\1\pip-install-ndvr4b84\ctypesgen\setup.py", line 13, in <module>
        import ctypesgencore
      File "C:\Users\<user>\AppData\Local\Temp\1\pip-install-ndvr4b84\ctypesgen\ctypesgencore\__init__.py", line 56, in <module>
        import processor
    ModuleNotFoundError: No module named 'processor'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\<user>\AppData\Local\Temp\1\pip-install-ndvr4b84\ctypesgen\
````

After manually installing processor I get the following error:

2. 
````
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<user>\AppData\Local\Temp\1\pip-install-uyrv77b3\ctypesgen\setup.py", line 13, in <module>
        import ctypesgencore
      File "C:\Users\<user>\AppData\Local\Temp\1\pip-install-uyrv77b3\ctypesgen\ctypesgencore\__init__.py", line 57, in <module>
        import printer
    ModuleNotFoundError: No module named 'printer'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\<user>\AppData\Local\Temp\1\pip-install-uyrv77b3\ctypesgen\
````

After installing printer manually, I get the following message:
````
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<user>\AppData\Local\Temp\1\pip-install-a8sygkpg\ctypesgen\setup.py", line 13, in <module>
        import ctypesgencore
      File "C:\Users\<user>\AppData\Local\Temp\1\pip-install-a8sygkpg\ctypesgen\ctypesgencore\__init__.py", line 60, in <module>
        import descriptions
    ModuleNotFoundError: No module named 'descriptions'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\<user>\AppData\Local\Temp\1\pip-install-a8sygkpg\ctypesgen\
````

I tried installing `descriptions` manually, but I got the following message:

````
ERROR: Could not find a version that satisfies the requirement descriptions (from versions: none)
ERROR: No matching distribution found for descriptions
````

I saw on the [ctypesgen github page](https://github.com/davidjamesca/ctypesgen/issues/54) that this is some kind of error with python 3 and that there is a more up-to-date version available, but it's not on pypi. I'm also not sure if this will work with

Any suggestions on how to get gpkit installed? I haven't been able to get running using anaconda either.

Thanks,

Kyle

**Comment by altendky** [comment]
It looks like gpkit is still py2 only.

https://github.com/convexengineering/gpkit/blob/e5eefec722e07740367a28619216427f62af8304/gpkit/small_scripts.py#L10

If you install with Python 2 it might work.  You don't really want to install the `processor` or `printer` modules etc.

**Comment by bqpd** [comment]
Yup, unfortunately we only support Python 2.7 right now. Python 3 support will be coming this summer, but it won't support MOSEK8 and I still need to work out how to implement something like our current literate-programming model with the changes to Python 3's `exec`.

**Comment by bqpd** [comment]
(that said, if you have a specific usecase and are planning to use cvxopt, the `py3` branch may be able to accomodate your needs, though be warned that it's not fully supported yet)

**Comment by kjgoodrick** [comment]
Got it, thank you both for your help!

**Comment by bqpd** [comment]
@kjgoodrick @altendky, GPkit is now (mostly) compatible with Python3, except for the parse_variables notation.
