### ISSUE TITLE
savemat() formatting file names incorrectly

### ISSUE THREAD

**Issue by courtin** [convexengineering/gpkit#1411]
When using the .savemat() function with gpkit 0.9, vector variable names can have '[:]' appended to the end, which causes matlab errors.  

Adding `replace("[:]", "")` to the line below seems to resolve the issue.

https://github.com/convexengineering/gpkit/blob/20d82e32a4198c79cfb5e8a0cc918b0f28015a4b/gpkit/solution_array.py#L462

**Comment by bqpd** [comment]
oops yup great call. I'lll use exclude=["vec"] instead of replace, but
should def change this

**Comment by bqpd** [comment]
With https://github.com/convexengineering/gpkit/pull/1412 `.savemat()` will also exclude unnecessary lineage from variable names (e.g., if only the Wing model has an variable `x`, it will be stored as `x`, not `Wing.x`). If you want full model names for every variable, call `.savemat(excluded=["vec"])`

(@philippekirschen-vh1 this may be relevant for your use as well?)

**Comment by lochieferrier** [comment]
would just like to drop a note and say thanks for the continued dev, use
GPkit every day in my work... it's too awesome to die! :)
