### ISSUE TITLE
repr_conventions ValueError: Cannot compare Quantity and <type 'float'>.

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1418]
I'm going to keep bombarding gpkit with issues, my bad. This occurs in the SPaircraft, python3 branch tests. I get an issue at line 42 of repr_conventions.py
```python
if (val > np.pi/12 and val < 100*np.pi  
```
which is
```python
ValueError: Cannot compare Quantity and <type 'float'>
```
Full test report is [here](https://acdl.mit.edu/csi/job/gpkit_ResearchModel_SPaircraft_PR/313/buildnode=macys_VM,optimizer=mosek/testReport/junit/gpkit.tests.from_paths/TestFiles/test_SPaircraft_py_mosek/).

**Comment by whoburg** [comment]
keep em coming!

**Comment by bqpd** [comment]
same issue as fixed by https://github.com/convexengineering/gpkit/pull/1414

**Comment by dev10110** [comment]
Hi, 

Ive just had this issue again, specifically when calling solution.summary()

The error statement:
`ValueError: Cannot compare Quantity and <class 'float'>`

Full error traceback is attached as a txt for convenience. 
[gpkit_error_traceback.txt](https://github.com/convexengineering/gpkit/files/3715199/gpkit_error_traceback.txt)


Reporting a minimal model and the associated error command:



**To recreate issue:**

******

`import pickle
import numpy as np
from gpkit import Model, Variable, Vectorize
from gpkit.constraints.tight import Tight
from gpkit.constraints.loose import Loose
from gpkit.constraints.bounded import Bounded

from gpkit import ureg as u`

`
class SimpleAircraft(Model):
    
    def setup(self):
        
        constraints = []
        components  = []
        
        M_0       = self.M_0       = Variable('M_0', "kg", "Mass of aircraft")
        M_payload = self.M_payload = Variable('M_{payload}', "kg", "Mass of payload + crew")
        M_empty   = self.M_empty   = Variable('M_{empty}', "kg", "Mass of empty aircraft")
        M_fuel    = self.M_fuel    = Variable("M_{fuel}", "kg", "Mass of fuel")
        M_dry     = self.M_dry     = Variable("M_{dry}", "kg", "Mass of dry aircraft (payload + empty)")
        
        g_0 = self.g_0 = Variable("g_0", 9.81, "m/s^2", "Acceleration due to gravity")

        constraints += [Tight([M_0 >= M_fuel + M_dry])]
        constraints += [Tight([M_dry >= M_payload + M_empty])]
        
        # empty weight fraction
        fit_A =  0.97 #Using Table 3.1 of Raymer, Jet transport
        fit_C = -0.06 #Using Table 3.1 of Raymer, Jet transport
        fit_K_vs = 1.00 # assumes fixed sweep
        constraints += [Tight([M_empty/M_0 >= fit_A*(M_0/(1.*u.kg))**fit_C*fit_K_vs])]
        
        return constraints, components
        
        
AC = SimpleAircraft()
M = Model(AC.M_0, Bounded(AC))


sol = M.solve()

sol.summary()
`

**Comment by 1ozturkbe** [comment]
Hey, I tried to recreate your issue on my machine and couldn't. Also, the way you have defined your constraint is as we intended. 
Can you doing ```from gpkit import units``` and replacing ```u.kg``` with ```units('kg')``` and see if that makes a difference? Also, I don't know if you meant to put parentheses around fit_C*fit_K_vs.

**Comment by 1ozturkbe** [comment]
It seems to me like that should fix your error, I hope it works. 
The issue is that ureg units are not Monomial instances unlike gpkit.units, and therefore do not have str_without() for printing purposes. @bqpd is this something we should address?

**Comment by bqpd** [comment]
@dev10110 thanks for submitting this. Your code runs for me; try using the latest versions of pint and gpkit, if you're not already. Also, as @1ozturkbe says, `gpkit.units` should almost always be used instead of `gpkit.ureg`.

**Comment by bqpd** [comment]
@1ozturkbe naw, if for some reason a Pint unit ends up in a GPkit structure that's 1) probably a bug and 2) should properly print its str representation since it doesn't have a str_without. (that's what try_str_without is for)
