### ISSUE TITLE
returned Model of a .setup has __.cost = Monomial(1). 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1420]
This has been a thing that has bothered me for a long time. It may be because I'm still a little confused about the difference between __init__ and setup. Consider the following:
```python
class SPThing(Model):
    "a simple SP"
    def setup(self):
        x = Variable("x")
        y = Variable("y", 2.)
        z = Variable("z")
        with SignomialsEnabled():
            m = Model(1/z, [z <= x**0.5 + y, x*z == 2])
        return m
```
When you call ```m = SPThing(), print(m.cost)```, this cost is 1, and not 1/z. However, if you define the class as:
```python
class SPThing(Model):
    "a simple SP"
    def setup(self):
        x = Variable("x")
        y = Variable("y", 2.)
        z = Variable("z")
        with SignomialsEnabled():
            constraints = [z <= x**2 + y, x*z == 2]
        self.cost = 1/z
        return constraints
```
then m.cost has the 'right' behavior and the right constraints. I'm just not sure that the previous definition has the desired behavior. I see that in Model.__init__ we have ```start_args = [cost, constraints]''', but we are actually dropping the cost? It seems like the lines 62 in model.py
```python
            cost = self.cost
```
we are intentionally assigning cost to None, then on line 67
```python
        cost = cost or Monomial(1)
```
causing all models created with setup methods to have cost = Monomial(1). Please help me clear my confusion.

**Comment by bqpd** [comment]
Setting `self.cost` in a setup method is the desired way to set the cost. In your second `SPThing`, the cost is still stored; in the model object returned as the constraints list, such that

```python
spthing2  = SPThing()
assert spthing2.cost == 1
assert spthing2[0].cost == 1/spthing["z"]
```

**Comment by whoburg** [comment]
Is it documented somewhere that the `setup` method of a `Model` should return a list of constraints and never a `Model`?

**Comment by bqpd** [comment]
It's fine if it returns a model! It'll just be treated like any other
constraint. The documentation actually avoids setting cost from within
setup, since that's not a super encouraged use; instead a new model is
created every time before solving.

>

**Comment by whoburg** [comment]
> The documentation actually avoids setting cost from within setup, since that's not a super encouraged use

> Setting self.cost in a setup method is the desired way to set the cost

Which is it? (and is this documented)?

**Comment by whoburg** [comment]
Reopening just because it seems like this is unclear enough that we should make sure it is documented.

**Comment by bqpd** [comment]
added to #1280

**Comment by whoburg** [comment]
great... and @bqpd can you please clarify which of the two quotes above is correct? Is setting cost in setup desired or not super encouraged?

**Comment by bqpd** [comment]
If you absolutely have to set the cost in the setup method, `self.cost` assignment is the way it should be done ("desired"), and it's supported for backwards compatibility...but I don't document that because I think emphasizing that the cost function is something to be chosen at solve time, not model definition time is very important (because there's never only one possible cost function).

**Comment by whoburg** [comment]
goootcha, I like that philosophy.
