### ISSUE TITLE
type(Variable.units) for unitless or un-united variables is NoneType.

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1427]
This is something that shows up a lot, and is quite a hurdle if you are dealing directly with Variable objects. Shouldn't the type default to a unitless Quantity? This creates issues when you call for example:
```python
k.units**v
```
where k.units is Nonetype.

**Comment by bqpd** [comment]
It's a speed optimization :grimacing:. Slightly archaic, we could probably replace it with ureg.dimensionless now. Alternately use `(k.units or 1)**v`

**Comment by 1ozturkbe** [comment]
Arg, I guess this is good and I will deal with it. Highly doubt most people have to deal with this day-to-day anyways.
