### ISSUE TITLE
Substitutions mystery for a simple PosyIneq

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1436]
Just found something interesting that is somewhat concerning...
Here is a MWE. 
```python
from gpkit import Variable
a = Variable('a')
b = Variable('b')
c = a <= b**2
subs = {b:2}
c.as_posyslt1(subs)
```
returns  [gpkit.Monomial(a*b^-2)]. And c.substitutions shows up empty. 
On the other hand, the following:
```python
c = a*b**2
c.sub(subs)
```
returns gpkit.Monomial(4*a), as I would expect. What's the exact difference?

**Comment by bqpd** [comment]
`as_posyslt1` assumes that it's getting passed a well-formed substitutions dict (i.e. no strings, no Variables, etc.) so you need to pass it `{b.key: 2}`

**Comment by bqpd** [comment]
(this assumption is represented by the `parsedsubs=True` argument passed in https://github.com/convexengineering/gpkit/blob/master/gpkit/nomials/math.py#L500)
