### ISSUE TITLE
Printing sol.table()/summary() with large arrays is unreadable.

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1444]
This is for EGPAnet, where I am trying to read the output of very large VectorVariables, some of them 20 long. GPkit likes printing these in a nice long vertical vector, which makes the output actually exceed the length allowed by cmd. I will make a fix.

**Comment by bqpd** [comment]
what does `allowed by cmd` mean?

**Comment by bqpd** [comment]
the way row-size is chosen is a bit overly complicated, so feel free to tag me in on this on

**Comment by 1ozturkbe** [comment]
As in, 'my terminal is blowing up, past its ability to contain text', since the output is many pages long. Now that I look at the f'ns for table() I would like some help here :)

**Comment by 1ozturkbe** [comment]
(this model has 600 vars or so, and it's all presented in a one dimensional vector form haha)

**Comment by bqpd** [comment]
I don't think users should be able to specify `ncols`, because it makes it impossible to distinguish 2D and 1D variables...I like the notion of cutoffs, though.

**Comment by bqpd** [comment]
What's your ideal table output?

**Comment by 1ozturkbe** [comment]
I think it'd be like this...
[ X X ... X X ;
  X X ... X X ;
   |  |      |   | ;
  X X ... X X ;]

**Comment by 1ozturkbe** [comment]
I think it's rather impossible to look at more than 5-8 values per row of anything anyways, so we might as well have some arbitrary cutoff.

**Comment by bqpd** [comment]
in a fixed-width format, is this equivalent? (arbitrary cutoff doesn't work for all use-cases)

```
[ X X ... X X
X X ... X X
...
X X ... X X]
``

**Comment by bqpd** [comment]
what about this instead?

```
[ x1
  x2
  ...
  x599
  x600 ]
```

**Comment by 1ozturkbe** [comment]
Hmmm, it is useful to have some notion of 1D/2D I guess. Would it be possible to specify multiple rows for 2D vectors, single row for everything else.

**Comment by bqpd** [comment]
yup!

**Comment by bqpd** [comment]
I'm thinking default `maxrows = 50`, and anything above that gets chopped down to 50.

**Comment by 1ozturkbe** [comment]
Oh I was thinking having rows instead of columns for each output. Columns are confusing because the units and descriptions start floating far away.

**Comment by bqpd** [comment]
unfortunately having more than a few columns destroys readability in many terminals

**Comment by bqpd** [comment]
yeah, i think maybe just taking anything that exceeds max rows and showing
it in a single line as [ x1 ...(98 values
skipped)... x100] is making the most sense to me

**Comment by 1ozturkbe** [comment]
But then why not just show maxrows? (eg. [X X ... X X])?

**Comment by bqpd** [comment]
not following how that's different?

**Comment by 1ozturkbe** [comment]
oh, it's instead of skipping 98 values, you put however many was in maxcols.

**Comment by bqpd** [comment]
Looking at this a bit later, I think GPkit should always print all info - users can filter by changing which tables/variables they print.
