### ISSUE TITLE
Best way to track "parents" of operations such as posy.chop or constraint.as_posyslt1()

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1451]
This is a design discussion @bqpd since I will need to do this for some new functionality I'm planning for robust. I would like to track the original parents of each new constraint or GPkit object created in robust so I can easily call some attributes of the parents. I could do this by adding .parent to every robust object AND every gpkit object, but that seems horrendously cumbersome. Is there any code magic that can be done instead?

**Comment by bqpd** [comment]
yup, I'd just add .parent! that is the magic! everything is a linked list 🤩

**Comment by bqpd** [comment]
a lot of `.parent` in https://github.com/convexengineering/gpkit/pull/1463
