### ISSUE TITLE
Jenkins script cleaning

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1455]
@bqpd one of the things that we should do is follow the example of Bob and ESP in the way he runs tests. This would involve:
- [ ] Pulling each script from the configurations and saving them in a (private) repo. 
- [ ] Figuring out the common parts of each script, and putting into a 'master' script. 
- [ ] Only calling scripts from the common repo when we need, not from within the config files in Jenkins. 
You and I now have a private epo in acdl called JenkinsGPkit that we can use for this purpose.

**Comment by bqpd** [comment]
sounds great!
