### ISSUE TITLE
Mosek macOS Catilina

### ISSUE THREAD

**Issue by trevorVlong** [convexengineering/gpkit#1458]
Seems to be an issue finding and using any form of mosek on macOS Catilina. Mosek passes all tests in installation then cannot be found when called for as a solver. 

Interestingly, leaving m.solve() blank leads to use of mosek cli

**Comment by bqpd** [comment]
I'd recommend just using mosek_cli or mosek9, then! It's probably yet
another macOS linking change, and we're moving away from support for the
compilation of new binaries with mosek 8.
