### ISSUE TITLE
How to solve the case when object  is prod of a ratio between two posynomials 

### ISSUE THREAD

**Issue by zhuwenxing** [convexengineering/gpkit#1462]
Hi,
 I am working on using gpkit to solve the problem of power control in wireless. The reference is [
Power Control By Geometric Programming](https://www.princeton.edu/~chiangm/gppower.pdf) . The problem is defined in section IV, and it is an SP problem. In the example, you have shown some SP problems. However, they are the cases that constraints not satisfied. But in my project, the case is the object is not satisfied.  
The algorithm is as follow:
![image](https://user-images.githubusercontent.com/12268675/75411429-27ed1900-595a-11ea-95d2-02d1bba8a8d8.png)

I didn't find a similar example! So, how to solve such type of problem?
can ```SignomialsEnabled```  work for this case in below? 
```python
with gpkit.SignomialsEnabled():
    obj = objfunc
```

**Comment by bqpd** [comment]
hi @zhuwenxing! Welcome to GPkit.

You can use a Signomial objective by creating a new variable `cost = Variable("cost")` and adding a constraint `cost >= [ your signomial here ]`

**Comment by bqpd** [comment]
note that if your signomial might go negative overall you should offset it by a large positive value.

**Comment by zhuwenxing** [comment]
Hi, Thanks for your advice! Here, I have some additional questions
* How can we get each monomial of a posynomial?
I notice that a posynomial object has ```cs``` and ```exps``` attribute so that we can use them to get each monomial! I want to know is there a quick way to get each monomial?
A key step in the pseudo-code that I refer to needs to calculate a coefficient in the following way:
![image](https://user-images.githubusercontent.com/12268675/75426913-85945c00-5980-11ea-9d72-2f4b2de618e4.png)

* prob() function in gpkit
Because my objective is a prod of many posynomial, in NumPy or Matlab, we can use np.prod() or prod() to realize that. In gpkit, do we have any function to realize that?
I use ```np.prod(items)```(items is a list, each element is a posynomial),  and it seems work!


Thanks in advance!

**Comment by bqpd** [comment]
1. `p.chop()` will return a list of the monomials in `p`
    - the boxed quantity would thus be `alpha = [m.sub(sol)/p.sub(sol) for m in p.chop()]`
2. That'll work, but a slightly faster method is `from gpkit.nomials.array import NomialArray; NomialArray(items).prod()`

**Comment by zhuwenxing** [comment]
That helps me a lot, thanks!
Gpkit is really powerful and convenient！Hope the document can be better and more detailed.

**Comment by bqpd** [comment]
You're more than welcome to help write some! It'd be great to have an example up for power control; if you write it I'll add it to the docs :)
