### ISSUE TITLE
Maximizing Sums

### ISSUE THREAD

**Issue by adishavit** [convexengineering/gpkit#1469]
I need to maximize the sum of bounded (constrained) variables. 
The objective minimizes and the docs say that to maximize I need to take reciprocal. However I cannot create the reciprocal of a sum (posynomial). I can minimize the sum of element reciprocals but this isn’t exactly what I need to maximize. 

Is there some other transformation/method I should use?

**Comment by rileyjmurray** [comment]
When it comes to geometric programs, there is no efficient algorithm that can handle maximization of a sum of decision variables. You can equivalently frame the problem as minimizing a negated sum ``-x - y - z ....``. When trying to minimize such a function in the geometric-programming framework, you have started to talk about "signomial programs." GPKit has functionality for finding locally optimal solutions to signomial programs-- this is described a bit in the web documentation.

**Comment by 1ozturkbe** [comment]
@rileyjmurray is right, unfortunately there is not clean way to do this. A hacky alternative to try is to min 1/prod(vars). Obviously this is not the same as a sum, so your experience may vary.

**Comment by adishavit** [comment]
Yes. I tried both min(1/prod(vars)) and min(sum(1/var_i)).

**Comment by 1ozturkbe** [comment]
Results? I'm assuming it didn't work. What you need is signomials:
```python
with SignomialsEnabled():
    constraints += [obj<= sum(vars)]
m = Model(1/obj, constraints)
```

**Comment by adishavit** [comment]
Actually, my use case is relatively easy (like DP with some quadratic constraints) so both approaches seemed to work on my initial tests. I will need further analysis with more rigorous test to see it fail.  
I will try your suggested Signomial approach which does seem to minimize the correct thing, I just hope it will not run much longer.

**Comment by bqpd** [comment]
Good luck!
