### ISSUE TITLE
cannot import name 'mosek_conif'

### ISSUE THREAD

**Issue by norheim** [convexengineering/gpkit#1484]
Installing v.0.9.9.1 with pip and running tests seems to run into some import issues(probably some python relative import problems, where somehow it can't find mosek_conif); installing it from local files however passes all tests:

One of the tracebacks from the tests:

```
lib\site-packages\gpkit\tests\t_solution_array.py", line 115, in test_result_access
    sol = m.localsolve(verbosity=0)
  File "C:\Users\johan\Miniconda2\envs\mdo\lib\site-packages\gpkit\constraints\prog_factories.py", line 124, in solvefn
    result = progsolve(solver, verbosity, **kwargs)
  File "C:\Users\johan\Miniconda2\envs\mdo\lib\site-packages\gpkit\constraints\sgp.py", line 137, in localsolve
    gen_result=False, **kwargs)
  File "C:\Users\johan\Miniconda2\envs\mdo\lib\site-packages\gpkit\constraints\gp.py", line 152, in solve
    solverfn, solvername = _get_solver(solver, kwargs)
  File "C:\Users\johan\Miniconda2\envs\mdo\lib\site-packages\gpkit\constraints\gp.py", line 43, in _get_solver
    from .._mosek import mosek_conif
ImportError: cannot import name 'mosek_conif'
```

**Comment by 1ozturkbe** [comment]
Did you install mosek9 using a local pip install?

**Comment by 1ozturkbe** [comment]
Also, mosek9 is only py3 compatible, it seems like you are using py2.

**Comment by norheim** [comment]
This is running python 3.6.7 and using mosek's conda installation (it's all installed into the same conda env); once again for some weird reason it works when installing from git, but not when installing from pip

**Comment by 1ozturkbe** [comment]
I don't know why it's a python import error. Can you run ```import gpkit; gpkit.build()``` and see which solvers are recognized? It seems like this is not GPkit's fault.

**Comment by bqpd** [comment]
if this is a pip install it might be that i forgot to add the file to
MANIFEST...

**Comment by norheim** [comment]
If it's helpful here is the build print; @bqpd might be what you are mentioning
```
Found no installed solvers, beginning a build.
# Moving to the directory from which GPkit was imported.
Started building gpkit...

Attempting to find and build solvers:

# Looking for mosek
# no mosek version folders (e.g. '7', '8') were found in the mosek directory "C:\Program Files\Mosek"
# Did not find mosek
# Looking for mosek_cli
#   Trying to run mskexpopt...
#     Calling 'mskexpopt'
##
### CALL BEGINS
'mskexpopt' is not recognized as an internal or external command,
operable program or batch file.
### CALL ENDS
##
# Did not find mosek_cli
# Looking for mosek_conif
#   Trying to import mosek...
# Found mosek_conif in Python path
# Looking for cvxopt
#   Trying to import cvxopt...
# Found cvxopt in Python path
...finished building gpkit.

Found the following solvers: mosek_conif, cvxopt
#     Replacing directory env
.E............EEEEEEEEEEEEEx[:] <= w
.............................................EE..E.......E..EEEEEE.................EEEEEEE.EEEEEEEE.E...E......E.....EE.
EEE.EEEEEEEEEEE.....E..............EEEEEEE.E...........
```

**Comment by bqpd** [comment]
yup I forgot to put it in the MANIFEST D:

just pushed a new update to pypi, try pulling?

**Comment by 1ozturkbe** [comment]
@norheim any updates here?

**Comment by norheim** [comment]
Wait @bqpd , pypi's gpkit is from March 3rd. Are you sure the updates got pushed properly?

**Comment by bqpd** [comment]
oops good call I forgot to update the version number and pypi doesn't let
you overwrite existing versions. try now!

>

**Comment by norheim** [comment]
works like a wonder! thanks @bqpd !
