### ISSUE TITLE
Non-homogenous Vectorization

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#1486]
Related to #1465: 

Is there an elegant way to enable the following concept of vectorization with GPkit:

```python
with Vectorize(4): 
   self.HLM = HighLevelModels()
    with Vectorize([2, 3, 1, 1]):
        self.MLM = MidLevelModels()
        with Vectorize(2):
            self.LLM = LowLevelModels()
```
where the length of the middle level of vectorization must necessarily be equal to the degree of the top level of vectorization.

I'm trying to figure out an elegant way of allowing the 7 parallel mid-level models to share common parents. So in this example, the first two models share the same high-level model, models 3-5 share the same high-level model, and so forth.

Ultimately the lowest level variables in this example should have shape `(4,7,2)`.

Any suggestions?

**Comment by 1ozturkbe** [comment]
It seems to me like this is compatible with GPkit vectorization as follows, since the depth and width of the vectorization are square? 
```python
import numpy as np
from gpkit import Model, Vectorize
vecMatrix = np.array([[1,1,1,1], [2,3,1,1], [2,2,2,2]])
depth, width = vecMatrix.shape
models = [a, b ,c]
for j in range(width):
    with Vectorize(vecMatrix[0,j]):
        self.HLM = a
            with Vectorize(vecMatrix[1,j]):
                self.MLM = b
...
```
You could also probably write a cool nested Vectorization function for arbitrary shapes. I don't know if this is helpful or if you've already figured it out.

**Comment by 1ozturkbe** [comment]
Alright, I toyed with some ideas just now, and none of them were elegant.

**Comment by 1ozturkbe** [comment]
I think this is most elegant when there is a mapping... will post in a little bit, need breakfast.

**Comment by 1ozturkbe** [comment]
I don't have time to do this, but I think you could do a sequential mapping, where you generate LLMs, MLMs and HLMs with indices [x,y,z], [x,y] and [x], and recursively nest them as arguments to each other.
