### ISSUE TITLE
"SGP not convergent" warning should be affected by verbosity? 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1490]
I can add a PR for this as well as ConstantsRelaxed if you agree @bqpd.

**Comment by 1ozturkbe** [comment]
I guess you could put verbosity <= -1 but that's not really intuitive.

**Comment by bqpd** [comment]
naw I think it's a fundamental error, along the lines of divide-by-zero in
numpy. We could use warnings, like they do, to make it hideable, but I
don't think it's a "verbosity" thing...
