### ISSUE TITLE
License not found error

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1492]
When MOSEK can't find a license or it's out of date it gives the UNKNOWN status.  I usually lose a minute everyday trying to figure out what's wrong with my model before I remember that I need to log on to the VPN so the solver knows where to look for the license on the server. 

Any chance that a different error message can be printed out when the license can't be found or is out of date.

**Comment by bqpd** [comment]
I think `mosek_conif` gives a more sensible error message; for `mosek_cli` unfortunately the error code returned is platform dependent, but if you post it in this thread (should show up along with the UNKNOWN status) I can start catching them.

**Comment by bqpd** [comment]
For me on linux it returns 240
