### ISSUE TITLE
Model.children and Model.parent

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#1524]
Would it be straightforward to create children and parent attributes for all Model objects? Proposed usage:

```python
Mission.children = ["FlightProfile", "Atmosphere", "AircraftPerformance"]
AircraftPerformance.children = ["Aircraft", "FuselagePerf",.... ]
Aircraft.parent = "AircraftPerformance"
```

I understand it's possible to re-construct these by iterating over all model varkeys and using `lineage`, but it seems like it would be more elegant to create during model creation, i.e. execution of `Model.__init__`?

This would help with [visualizing](https://plotly.com/python/treemaps/) model structures. Related to #1088.

**Comment by 1ozturkbe** [comment]
This is similar to #1451 as well.

**Comment by bqpd** [comment]
Wouldn't be too hard (probably best to do as another thing the NamedVariable environment catches), but what's the reason you want the stored entries to be a string/list of strings instead of the model instances directly?

**Comment by pgkirsch** [comment]
Yea model instances probably make more sense. That's how I originally wrote it, I thought strings might be easier for the #1088 use case, but actually probably not.

**Comment by pgkirsch** [comment]
Not actually sure this is necessary for #1088 anymore though but would perhaps would still be a nice attribute to have.

**Comment by bqpd** [comment]
It's something I've dallied with adding a few times, but it always turns out to not quite be necessary...happy to add if there's a specific usecase though, like ended up happening with posynomials.

**Comment by bqpd** [comment]
Closing this until there's a specific usecase...
