### ISSUE TITLE
Redundant equality constraint causes issues with CVXOPT

### ISSUE THREAD

**Issue by nillst** [convexengineering/gpkit#1551]
When using CVXOPT, a redundant equality constraint will fail to solve and send the model into debug mode (see the example below). The model is feasible as demonstrated by the successful solve on the first go. Once in debug mode, the model is solved successfully with relaxed constraints but shows 0% relaxation.

As far as I have tried, redundant inequality constraints do not seem to have this issue.

Thoughts?

## Environment Information
- Python: 3.7.0
- GPkit: 0.9.9.9.1
- CVXOPT: 1.2.6

## Test model
```python
from gpkit import Model, Variable

a = Variable('a', 1)
b = Variable('b')
c = Variable('c', 2)
d = Variable('d')
z = Variable('z', 0.5)

# create a simple GP with equality constraints
const = [
    z == b/a,
    z == d/c,
]

# simple cost
cost = a + b + c + d

# create a model
m = Model(cost, const)

# solve the first version of the model (solves successfully)
m.solve(solver='cvxopt')

# add a redundant equality constraint
m.extend([
    z == b/a
])

# solver will fail and attempt to debug
m.solve(solver='cvxopt')
```

### Example Output
```
Using solver 'cvxopt'
 for 2 free variables
  in 5 posynomial inequalities.
Solving took 0.00302 seconds.
Using solver 'cvxopt'
 for 2 free variables
  in 7 posynomial inequalities.
Solving took 0.00111 seconds.
The model ran to an infinitely low cost; bounding the right variables would prevent this.
Since this model solved in less than a second, let's run `.debug()` automatically to check.
`
< DEBUGGING >
> Trying with bounded variables and relaxed constants:
>> Failure.
> Trying with relaxed constraints:
Solves with these constraints relaxed:
   0:    0% relaxed, from z = b/a 
                     to z <= a^-1·b 
>> Success!
```

**Comment by whoburg** [comment]
Hmm, it's surprising to see "`The model ran to an infinitely low cost`". This model's cost definitely seems bounded (should be 1.5 I believe).

**Comment by bqpd** [comment]
ah I think that's just my blanket dual infeasibility statement, I should be more exact.

Still, strange that this is dual infeasible!

**Comment by bqpd** [comment]
Also strange that it doesn't solve with relaxed constants

**Comment by bqpd** [comment]
newest master prints "<DEBUG> Model seems feasible without modification, or only needs relaxations of less than 1%. Check the returned solution for details." which is a little more clarifying

**Comment by bqpd** [comment]
confirmed that it solves with MOSEK

**Comment by bqpd** [comment]
it wouldn't be difficult to remove duplicate constraints on the gpkit side
