### ISSUE TITLE
API documentation is empty

### ISSUE THREAD

**Issue by akshayka** [convexengineering/gpkit#1564]
On the current version of the online docs, the API documentation appears to be empty.

For example (from https://gpkit.readthedocs.io/en/latest/autodoc/gpkit.constraints.html#module-gpkit.constraints.bounded):

![image](https://user-images.githubusercontent.com/1994308/141217308-e97caebc-a47d-4bd0-924b-fd52b20a1117.png)

It's an easy error to make with Sphinx (I've done it) but hard to catch, so just thought I'd mention it.

**Comment by bqpd** [comment]
Fixed (belatedly), thanks for the heads up!

Amusingly it was caused by a dependency change.
