### ISSUE TITLE
GPkit

### ISSUE THREAD

**Issue by nikozara** [convexengineering/gpkit#1565]
"Very simple problem: minimize x while keeping x greater than 1."
from gpkit import Variable, Model
# Decision variable
x = Variable("x")
# Constraint
constraints = [x >= 1]
# Objective (to minimize)
objective = x
# Formulate the Model
m = Model(objective, constraints)
# Solve the Model
sol = m.solve(verbosity=0)
# print selected results
print("Optimal cost: %.4g" % sol["cost"])
print("Optimal x val: %.4g" % sol["variables"][x])

**Comment by whoburg** [comment]
Closing as possible mistakenly created ticket, please feel free to re-open if there's a specific issue to report.
