### ISSUE TITLE
Document best practices for design exploration

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#181]
Related: we need documentation on options, best practices, and terminology for exploring Pareto frontiers. This could morph into a tech report or tutorial-style paper.

**Comment by whoburg** [comment]
As part of this, we need to connect our view of the multi objective world with the epigraph trick. Here's a description of the epigraph trick, shamelessly stolen from the transcript of a Boyd lecture:

```
Here’s a simple trick. It’s called the epigraph trick. It’s actually quite useful, and it’s widely used in practice. Let’s see how that works. I mean it’s really dumb. Here’s what it is. You wanna minimize f0. You introduce a new scalar variable t, and you introduce this new constraint, which is f0 – this is basically f0(x) = t, and you minimize t. Now this is kinda dumb because if you solve this problem, first of all you’d be an idiot to choose any t other than f0(x) = t. Not an idiot, you’d just be – that t couldn’t possibly be optimal is the point because your goal is to minimize t. However, I cannot adjoin this to this problem. It is an equivalent problem to write equals here. That’s absolutely equivalent to the original problem. Unfortunately, it’s not convex unless f0 is affine. However, with a less than or equal to, it’s convex.

It’s a really dumb thing. Let me just draw this. Here’s a function that you wanna minimize like this. The original problem basically says find the point here that minimizes f0. This one does this ridiculous thing and introduces a new t that’s up here like that, and it says that’s your feasible set or something like that, and then it says go as far as you can in the direction –t, right? Like that, actually I guess the direction is -1, and you would recover this point here. By the way, this has immediate practical application. This says for example that if you’re gonna write a code to solve convex problems, you don’t need to – without any loss of generality, you can just minimize a linear objective. That’s quite standard. So you look on – if you go to Google and type C source and then some name of some convex problem, you will find it’ll just – many times, they won’t even say it. It’ll just say it solves the following problem, and it’s a linear objective. You go hey, I can’t use this. My objective is not linear. Well, it’s just expected that you know this, so this is just expected. By the way, it’s generally not in the documentation which is actually interesting because that’s how widely this is supposed to be known. It’s also how unhelpful the documentation is. So this is the epigraph trick, and you’ll see this used quite frequently. Oh, the other thing you’ll hear is this. You’ll actually have people say just without loss of generality, the objective can be assumed to be linear because that’s a linear objective. It’s a linear function of x and t. So that’s just completely standard.
```

**Comment by whoburg** [comment]
My condensed/shortened version or interpretation of the epigraph trick:
There is nothing special about the objective. You can always formulate your problem such that everything interesting is in a constraint. Why? Because I can always take whatever you claimed was the objective, `f_0(x)`, change the objective to `t`, introduce the constraint `t >= f_0(x)`, and I have an equivalent problem. Note this all assumes `f_0` is convex.

**Comment by whoburg** [comment]
GP tutorial (http://stanford.edu/~boyd/papers/gp_tutorial.html), section 3.2, describes the "weighted sum method", which might inspire a better name for the current `MOO`?

**Comment by bqpd** [comment]
Ooh, I like "weighted sum method". I've also been using "linear-interpolation".

**Comment by bqpd** [comment]
@whoburg, does that commit answer your original issue?

**Comment by whoburg** [comment]
``composite_objective`` is a great start. I think we still need to work up more documentation on best practices, including understanding when it's better to use a composite objective vs sweeping constraints directly. (we might need to answer that ourselves before we attempt to document it).

**Comment by bqpd** [comment]
Heh, indeed.

**Comment by bqpd** [comment]
Gosh, we know a lot more about this now than when this issue was opened. Sounds like an interesting lab-wide paper to write?

**Comment by bqpd** [comment]
@1ozturkbe, this is kinda your thesis, right? :+1:

**Comment by 1ozturkbe** [comment]
To a certain extent... I am leaning more towards model creation rather than model use. But perhaps next paper can be 'Design Exploration using GPkit'? :P
