### ISSUE TITLE
add "Signomial Programming 101" to docs

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#207]
Looking for the detailed math / algorithm steps, as opposed to the user interface.

**Comment by whoburg** [comment]
Should also address the points in this commit comment: https://github.com/convexopt/gpkit/commit/01840da4177ccdea27328a465a9d35bb5099eb56#commitcomment-10776264

**Comment by bqpd** [comment]
Draft explanation of current constraint formation:

For constraint `p0 - q0 + c0 <= p1 - q1 + c1`, where all p and q are posynomials without constant terms and all c are constants (positive, zero, or negative).

1. Subtract (p1 - q1) from both sides.
   *  `p0 - p1 + q1 - q0 + c0 - c1 <= 1`
2. Simplify the left-hand side
   * `p2 - q2 + c2 <= 1`
3. If c2 is positive, end. If c2 is less than 1, subtract it from both sides and then divide both sides by (1 + c2)
  * `(p2 - q2)/(1 - c2) <= 1`

**Comment by bqpd** [comment]
Draft explanation of current SP algorithim:

1. Seperate monomials with negative coefficients from those with positive in each constraint
  * in essence, `s0 <= 1 \to p0 - q0 <= 1`
2. If we have an initial guess `xk`, form `mq0`; the monomial approximation of `1+q0` about `xk`.
  * See 'monomial approximation', below
3. Divide each `p0` by `mq0` that is, `p0 - q0 <= 1 \to p0 <= 1 + q0 \approx p0/mq0 <= 1`
4. If we do not have an initial guess, presume `q0` is equal to zero, and proceed with the GP approximation.

**Comment by bqpd** [comment]
Draft explanation of monomial approximation (feel free to edit + clarify!)

1. We want the monomial approximation of `p0`. Since monomials are a straight line in logspace, this is the same as wanting the gradient `d ln(p0)/d(xk)`, where `xk` is the point around which we are linearizing. 
2. Let `pk = p0(xk)`
3. For a given variable `xi` and inital value `xik`, this is equal to `eik = xik * dp0/dxi(xk) / pk`
4. The overall monomial approximation is thus proportional to the product of each variable raised to its logspace slope, or `mv0 = \prod_i xi^eik`
5. The proportional constant is clearly `pk/mv0(xk)`, so that the final answer is `mp0 = pk/mv0(xk) * \prod_i xi^eik`

**Comment by bqpd** [comment]
Draft explanation of new SP inner loop (@whoburg, please correct / flesh out)

1. If the GP approximation of the SP alg above is primal-infeasible, find the nearest feasible point
2. Using that point as `xk`, construct a new GP approximation
3. Repeat until GP approx is feasible, (at most `N` times)

**Comment by bqpd** [comment]
(@whoburg, does the above look reasonable?)

**Comment by whoburg** [comment]
I want to look through these in detail after the #282 GP refactor. (I want to follow along with the descriptions in code that won't change soon).

My plan is to start converting these to a pdflatex version (help welcome), as I think many of the details we're fleshing out haven't been documented in the literature.

**Comment by bqpd** [comment]
@whoburg, this issue seems ripe for an exciting documentation party!

**Comment by whoburg** [comment]
sounds good. Some of the explanations above seem to have some 1 vs 0 confusion (e.g. the first step of the first explanation)

another issue that myself and others keep stumbling on and that would be good to clarify has to do with projection of points during monomial approximation. Easiest to explain the confusion via whiteboard drawings or plots; just making a note here so we don't forget to cover it.

**Comment by bqpd** [comment]
I'm 200% for more plots in the documentation.

**Comment by bqpd** [comment]
also include https://github.com/convexengineering/gpkit/issues/862
