### ISSUE TITLE
Make project template

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#229]
@whoburg

I’m thinking there are several categories (formats) of example we might want to create:
- ipython notebook (quickest to iterate; worst for displaying to the world, in my opinion)
- html or rst format (with e.g. embedded code and math)
- latex format (e.g. for a paper)

For the second and third options, it would be great to have a template Makefile that runs code, creates plots, compiles, etc…

---

@bqpd

What about other scaffolding, like an example cadtoon or problem formulation format?

**Comment by bqpd** [comment]
Is this a documentation issue?

**Comment by whoburg** [comment]
yes, probably. Also, my feelings toward ipython notebooks are growing colder after seeing some new users struggle to get everything installed and, having never used an ipython notebook, feel pretty overwhelmed.

I think the notebooks sometimes present a barrier to entry that isn't there with inline code examples on the website.

**Comment by bqpd** [comment]
Yeah, since you made the text table really pretty I haven't gone back to ipynb.

**Comment by whoburg** [comment]
Semi-related to this and https://github.com/aeroa/gpkit-models/issues/7 is best practices for inserting commentary between the equations that define a model. Drela has a lot of good examples of simple commentary mixed with equations, like this: http://web.mit.edu/drela/Public/web/qprop/qprop_theory.pdf.
