### ISSUE TITLE
mosek builds with errors on windows (but works)

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#238]
carry-over issue from #223

**Comment by whoburg** [comment]
from @bqpd: 

I've built MOSEK on a Windows 8 machine, so it looks like it might be a mingw and/or permissions issue on the Jenkins VM. But now all the mosek_cli tests pass.

No change in the cvxopt condition.

@galbramc

**Comment by bqpd** [comment]
It's even weirder; MOSEK builds the bits we need _after_ throwing a compiler error...

**Comment by galbramc** [comment]
I agree it's very odd. I don't know what that initial failure is trying to
do.

Let me know if you cannot reproduce this on your Windows 8 machine.
