### ISSUE TITLE
refactor multi-solver unit testing

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#258]
We should revisit the structure of `t_model.py`, which currently runs every unit test for every solver, as well as other unit tests.
- [ ] Determine which tests should be run for all solvers (anything that requires a solver?), and which should not involve a solver at all.
- [ ] Reorganize unit tests according to above.
- [ ] As suggested by @bqpd, in tests where the outcome should not require a solver to be called, pass in some sort of null solver object to ensure this is the case.
- [ ] test that infeasible GP raises `RuntimeWarning` for all solvers 
- [ ] have a way for tests to specify which solvers they should be run for

**Comment by bqpd** [comment]
Solver runtime on personal computers should stay below 5s; tests can be moved from running for all solvers to running for only one solver as necessary.

**Comment by bqpd** [comment]
We have all this! Somewhat ad-hoc, but this isn't the issue to organize it...
