### ISSUE TITLE
mutability differs between nomials and PosyArray

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#286]
I'm seeing some unexpected behavior when using `+=`, `*=`, etc. In particular, nomials and PosyArray act differently.

Here's a simple reference to a `Variable` (which inherits from `Signomial`). When we modify the reference, the original variable remains unchanged:

``` python
In [1]: from gpkit import Variable, VectorVariable

In [2]: x = Variable('x')

In [3]: x_ref = x

In [4]: x_ref += 5

In [5]: x
Out[5]: gpkit.Variable(x)

In [6]: x_ref
Out[6]: gpkit.Posynomial(5 + x)
```

With a `VectorVariable` (which inherits from `PosyArray`), the behavior is completely different:

``` python
In [7]: y = VectorVariable(2, 'y')

In [8]: y_ref = y

In [9]: y_ref += 5

In [10]: y
Out[10]: gpkit.PosyArray([5 + y_(0,), 5 + y_(1,)])

In [11]: y_ref
Out[11]: gpkit.PosyArray([5 + y_(0,), 5 + y_(1,)])
```

Before we change anything, I'd like to understand the current behavior -- what in our implementation is causing this difference?

**Comment by bqpd** [comment]
I think this in particular is because of how np arrays implement +=, but I bet there's examples that don't hinge on that.

**Comment by whoburg** [comment]
Well this simple numpy example agrees with you:

```python
In [1]: import numpy as np

In [2]: x = np.arange(4)

In [3]: x_ref = x

In [4]: x += 2

In [5]: x
Out[5]: array([2, 3, 4, 5])

In [6]: x_ref
Out[6]: array([2, 3, 4, 5])
```
Note this behavior differs from that of int and float:

```python
In [7]: t = 3.

In [8]: t_ref = t

In [9]: t_ref += 1

In [10]: print t, t_ref
3.0 4.0
```
This immutability explains why our current implementation of `+=` for `Variable` makes some sense.

But I'm convinced that the behavior should be the same for `Variable` and `VectorVariable` -- anything else seems overly confusing for a user.

And I think I'm therefore ready to propose that a `Signomial` should be mutable. In other words, I'm suggesting that the behavior for the original example in this ticket should be (note: not implemented this way currently):

```python
In [1]: from gpkit import Variable, VectorVariable

In [2]: x = Variable('x')

In [3]: x_ref = x

In [4]: x_ref += 5

In [5]: x
Out[5]: gpkit.Posynomial(5 + x)

In [6]: x_ref
Out[6]: gpkit.Posynomial(5 + x)

In [7]: x_ref is x
Out[7]: True
```
Thoughts?

**Comment by cjk12** [comment]
I think this is because Python passes by reference.  Note:

```
>>>import numpy as np
>>> import copy
>>> x = np.arange(4)
>>> x_ref = copy.deepcopy(x)
>>> x+=2
>>> x
array([2, 3, 4, 5])
>>> x_ref
array([0, 1, 2, 3])
```

**Comment by bqpd** [comment]
This is 100% because of how numpy handles +=, and is also true of floats.
