### ISSUE TITLE
browser-based interaction without installing GPkit

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#297]
It should be possible to create js widgets that solve in real time (instead of pre-sweeping), without asking the user to install GPkit.

Realizing that this needs improvement in the future, the assumption for now would be that a user that doesn’t install GPkit will not modify the model. Example use case: we build a model in house and share it with an organization that interacts with it via sliders at a webpage.

Ideas we've kicked around (which may overlap):
- running a server that makes websocket connections, over which it accepts model parameters, resolves, and returns the result?
- create another `Solver` alongside mosek and cvxopt that functions via connecting to a server
- a method in `gpkit.interactive` that converts any model to an interactive html page (not requiring GPkit install) that can be viewed locally or posted somewhere online.

**Comment by bqpd** [comment]
* port gpkit to JS ;)

**Comment by whoburg** [comment]
oh goodness  :)

**Comment by bqpd** [comment]
(dumping some notes from looking into this)

https://stackoverflow.com/questions/4162749/convert-js-object-to-json-string

tornado websockets

**Comment by bqpd** [comment]
A websocket server exists, whooo
