### ISSUE TITLE
Better use of Sphinx for the documentation

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#303]
- [ ] Sphinx allows one to link to objects, functions, methods, etc, which could definitely enrich our docs. I think the process for linking between pages is done similarly, but I couldn't figure out how to do it for the GPkit 101 page...

**Comment by whoburg** [comment]
From https://github.com/convexopt/gpkit/commit/5776971c2ea2f232012d7605357b8eb7690b978c#commitcomment-12351413, we should
look into ways to switch the GPkit logo format (png vs svg) based on the output format...

**Comment by bqpd** [comment]
Per https://github.com/convexengineering/gpkit/issues/935, make sure all code in the docs is actually being run, and per https://github.com/convexengineering/gpkit/issues/847, emphasize the relevant lines
