### ISSUE TITLE
nomials.py should not set __class__

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#307]
In `nomials.py`, `__class__` attributes are set too freely. This causes subclassing to not work as expected -- `super(MySubType, self).__init__()` returns objects that are not of type `MySubType`, because `__init__` resets the class.

Better to find a way to call `super()` properly, and avoid setting classes.

May need a new way for operator-overloadings to choose among `Monomial`, `Posynomial`, etc as part of this.

**Comment by bqpd** [comment]
Agreed! The reason it's set up this way right now is partly to handle all the different input argument cases; with those simplified, this should be able to be done much better.

**Comment by whoburg** [comment]
Ok, and I know I verbally agreed that those should be simplified; we can use this ticket to capture that change as well.
