### ISSUE TITLE
DSM for Model?

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#364]
Just reading about Design Structure Matrices (https://en.wikipedia.org/wiki/Design_structure_matrix), and realized it would be completely straightforward for us to write `Model.dsm()` that returns a sparse 2D array.

Jury still out on whether this is useful and whether it matches the gpkit philosophy. 

Related to the work @pgkirsch did on dependency graphs.

**Comment by bqpd** [comment]
@whoburg, is this still of interest?

**Comment by whoburg** [comment]
yeah probably of interest though I agree with the milestone of distant release.

We could chat with Bruce Cameron about the extent to which this is useful.

**Comment by bqpd** [comment]
(Sankey diagrams probably show this better for variables of interest)
