### ISSUE TITLE
Separate Model printing into "Variables" and "Equations"

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#389]
(so that each can be printed separately)

**Comment by whoburg** [comment]
sounds good.

**Comment by bqpd** [comment]
Also separate variables by model-name

**Comment by whoburg** [comment]
+1 +++1 on separating by model name. It's pretty distracting to see all the prepended stuff on every variable.

**Comment by bqpd** [comment]
Got the latter done in #429
