### ISSUE TITLE
Make gptutorial (Boyd paper) examples

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#396]
And add to docs. Here's one:

``` python
from gpkit import Variable, Model

# Declare decision variables
x = Variable('x')
y = Variable('y')
z = Variable('z')

# formulate the Model directly
prob = Model(y/x,      # objective
          [2 <= x,  # constraints
           x <= 3,
           x**2 + 3*y/z <= y**0.5,
           x/y == z**2])

# Solve the Model -- note, it's infeasible!
sol = prob.solve()

# Print results table
print sol.table()
```

**Comment by bqpd** [comment]
Should this be in the Model library repository?

**Comment by whoburg** [comment]
I feel this should be in `docs/examples` -- and it should move to the gpkit-models repo if `docs/source/examples` is moving there too.

**Comment by bqpd** [comment]
Hmm, I don't think it is?

**Comment by whoburg** [comment]
I think this should stay in `docs/examples` for now -- anticipating that some new users will either have just read the GP tutorial paper, or be familiar with it, so I think having these appear early in the docs makes a nice connection.

**Comment by bqpd** [comment]
I think this is not the direction the documentation is going in.
