### ISSUE TITLE
use classmethods to create multiple ways of constructing objects

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#446]
This is a proposal; comments welcome.

I propose that we follow the design guideline of _not_ writing `__init__` methods that accept multiple calling sequences. Instead, I think we should definitely allow multiple ways to construct an object, but do so using classmethods. Like this:

``` python
    @classmethod
    def frommodel(cls, m):
        return cls(m.cost, m.constraints)
```

This is pretty standard python design style, e.g. there's `dict.fromkeys`, and `date.fromordinal`, and `date.fromtimestamp`, etc.

**Comment by bqpd** [comment]
Oh man. This is such the right way to do this.

**Comment by bqpd** [comment]
relevant: http://pythoncentral.io/difference-between-staticmethod-and-classmethod-in-python/
https://stackoverflow.com/questions/12179271/python-classmethod-and-staticmethod-for-beginner
