### ISSUE TITLE
MWE generator

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#460]
For raising issues (like #454) with solver writers, it would be great to have a method along the lines of `generate_input_file(solver=)` for `GeometricProgram`.

For mosek, it would generate a `.eo` file like `expopt1.eo` here: http://docs.mosek.com/7.1/capi/Exponential_optimization.html. For mosek at least, it seems like this should be doable through the `mosek_cli` code?

Cvxopt is lower priority I think, but one could envision generating a `.py` file like the one inline at http://cvxopt.org/userguide/solvers.html#geometric-programming.

**Comment by bqpd** [comment]
hehe. A .eo file like the mosek_cli option generates? When that errors it leaves the file behind in your tmp folder: 

```
7
5
8

*c
1.00000000000000000000e+00
1.00000000000000000000e+00
1.00000000000000000000e+00
1.00000000000000000000e+00
1.00000000000000000000e+00
1.00000000000000000000e+00
1.00000000000000000000e+00
1.00000000000000000000e+00

*p_idxs
0
1
2
3
4
4
5
6

*t j A_tj
0 0 1.00000000000000000000e+00
3 0 -1.00000000000000000000e+00
1 1 1.00000000000000000000e+00
2 1 -1.00000000000000000000e+00
3 1 -1.00000000000000000000e+00
4 1 2.00000000000000000000e+00
5 1 1.00000000000000000000e+00
6 2 -1.00000000000000000000e+00
7 2 1.00000000000000000000e+00
6 3 1.00000000000000000000e+00
7 3 -1.00000000000000000000e+00
4 4 -1.00000000000000000000e+00
5 4 -1.00000000000000000000e+00
6 4 -1.00000000000000000000e+00
7 4 1.00000000000000000000e+00
```

Also you can call solve with a `path` argument to change the path, and I'll add a `clearfiles` argument to prevent it from removing the files afterwards.

**Comment by bqpd** [comment]
I'd call this a "MWE generator", I think.

**Comment by bqpd** [comment]
Milestone?

**Comment by whoburg** [comment]
MWE generator sounds good. Where's the `tmp` folder live?

For milestone, I think future is fine for now -- available to be worked on but not our most urgent issue.

**Comment by bqpd** [comment]
Depends on your system but generally at `/tmp`. If you have verbosity=3 for a mosek_cli solve, I think it tells you?

**Comment by whoburg** [comment]
aha! got it -- mine's at `/var/folders/6r/98btd1dj215001_h77p4mx3m0000gn/T/tmpztgdTi/gpkit_mosek`

**Comment by whoburg** [comment]
very low priority, but as part of this it might also be helpful to be able to generate these `.eo` files for models that don't generate an error -- I just now purposefully introduced an error in a model just to quickly get a `.eo` file.

**Comment by bqpd** [comment]
Ah, good call. You noticed that I added a `clearfiles` arg as mentioned above, so calling `m.solve("mosek_cli", path="/home/$USER/", clearfiles=False)` leaves `gpkit_mosek` and `gpkit_mosek.sol` in $USER's home directory.

**Comment by whoburg** [comment]
oh nice, that's helpful.

**Comment by bqpd** [comment]
You might also be able to use `path="."`, though I didn't test it.

**Comment by whoburg** [comment]
Here's an example of a cvxopt issue for which I'd like to be able to create a (non-GPkit-dependent) MWE ticket at https://github.com/cvxopt/cvxopt:

```pytthon
from gpkit import Variable, Model

x = Variable('x')
t = Variable('t')

m = Model(t, [t >= 1 + x])
sol = m.solve("cvxopt")
```
When this model is solved with cvxopt, the final status is `unknown`. Surprisingly, however, there are three minor changes, each of which separately causes cvxopt to solve the problem successfully:

1. Change the `1` to `50` (or something larger):
```python
from gpkit import Variable, Model

x = Variable('x')
t = Variable('t')

m = Model(t, [t >= 50 + x])
sol = m.solve("cvxopt")
```
(solves successfully)

2. Eliminate `t` and move `1 + x` to the objective:
```python
from gpkit import Variable, Model

x = Variable('x')
t = Variable('t')

m = Model(1 + x, [])
sol = m.solve("cvxopt")
```
(solves successfully)

3. Add `x**0.1` to the objective, which confusingly adds *even more* downward pressure on `x`:
```python
from gpkit import Variable, Model

x = Variable('x')
t = Variable('t')

m = Model(t + x**0.1, [t >= 1 + x])
sol = m.solve("cvxopt")
```
(solves successfully)

**Comment by whoburg** [comment]
See #977 for an example of a near-dual-infeasible gp that gets different answers on mosek 7 and mosek 8 (despite those having the same tolerances according to the docs?)

**Comment by whoburg** [comment]
@bqpd 
This is becoming high priority -- would like to work with mosek to provide some example GPs for their internal development work.

Basic functionality needed is a method of `GeometricProgram` that can dump out the corresponding `.eo` file.

Would like to be able to just copy/paste from the terminal, or write out the file to a specific path, as opposed to digging around in `tmp/` directories.
