### ISSUE TITLE
Controlpanel seems to break with vector variables

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#485]

**Comment by bqpd** [comment]
[relevant ipynb](https://www.dropbox.com/s/5houv76rxru126x/RvsC.ipynb?dl=0)

**Comment by bqpd** [comment]
How do we want to fix this? Just by treating them as individual variables?

**Comment by whoburg** [comment]
Need more information -- including more details on the failure mode. Does controlpanel fail for any model that involves vector variables? When a constant (slider) is a vector variable? In some other case?

**Comment by bqpd** [comment]
Oh, it just doesn't know how to split them into sliders, that's all. Not a hard fix from a technical perspective, just an interface one.

**Comment by whoburg** [comment]
Got it. I support your suggestion above (treat as individual variables) for an immediate fix. In the future, we may want to consider a prettier layout where, for example, the sliders for a vector var are grouped and take up slightly less real estate -- but that's not needed immediately.

**Comment by bqpd** [comment]
Noted.
