### ISSUE TITLE
linear algebra tricks for assessing dual feasibility

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#527]
This ticket is an extension of #519. It is a work in progress. The ultimate goal is a systematic process for
- identifying monomials that require pressure to make a problem dual feasible, or
- suggesting substitutions (variable replacements) that would make a problem better conditioned, or
- suggesting changes to a model that would avoid solvers returning `UNKNOWN`, or
- other ideas/improvements enabled by studying the linear algebra of dual infeasible problems.

To get started, here's a simple GP:

``` python
from gpkit import Variable, Model
import numpy as np

CL = Variable("CL")
CD = Variable("CD")
V = Variable("V", "m/s", "cruise speed")
W = Variable("W", 200, "lbf", "weight")
rho = Variable(r"\rho", 1.2, "kg/m^3", "air density")
S = Variable("S", 190, "ft^2", "wing area")
m = Model(V*(W/(CL/CD)),
          [0.5*rho*CL*S*V**2 == W,
           CL**1.5/CD <= 20])
sol = m.solve()
```

As noted in #519, the problem above is primal and dual feasible, but becomes dual infeasible if the `1.5` is changed to any other number.

We could derive this fact by studying the A matrix. `m.gp().A.todense()` is

```
matrix([[ 1. , -1. ,  1. ],
        [-2. , -1. ,  0. ],
        [ 2. ,  1. ,  0. ],
        [ 0. ,  1.5, -1. ]])
```

This matrix has rank 2. The (middle) equality constraint rows are clearly linearly dependent, and the last row is equal to minus the first row minus half the second row. It's not obvious unless you've been thinking a lot about dual feasibility, but this matrix must have rank 2 in order to be dual feasible -- it needs to have a nullspace. Change the 1.5, and the matrix becomes rank 3 -- and the problem dual infeasible.

This implies that, as one example, it would have been possible to derive the `1.5` exponent automatically -- i.e. to tell a user what pressure is needed on a monomial involving the specific variables `CL, CD` in order for the problem to be dual feasible.

This isn't a fully-formed idea yet, but I bet there are a lot of useful things we would learn by studying this in more detail. Matlab computes matrix rank using an SVD. I wouldn't be surprised if we can get lots of useful information out of the SVD of A matrices.

**Comment by bqpd** [comment]
Dang, this sounds great.

**Comment by bqpd** [comment]
Covered in most cases by the bounds-checker that's been in the code for months; though that doesn't handle issues like those above, or cycles other than monomial equalities, it's very fast and can return results at the submodel level.

**Comment by whoburg** [comment]
Ok it's not the three year anniversary of this ticket yet, but I'll admit I dropped the ball on this. I'm still excited to look into it though! It could even make a great master's project for someone.

**Comment by whoburg** [comment]
Is the current bounds checker looking at the rank of the A matrix, or doing something more brute force?

**Comment by bqpd** [comment]
It's checking that variables are on the lesser-than / greater-than side of constraints, with logic to carry those pressures through equality constraints.

**Comment by whoburg** [comment]
hmm, interested to see whether these things end up being equivalent! E.g. see the 1.5 example above. I wonder if the carried-through pressures would have any useful relation to 1.5 here.

**Comment by whoburg** [comment]
in any case, I agree closing this for now is ok, until someone is ready to devote some thinking time to it.
