### ISSUE TITLE
discuss optimization pressures in the documentation

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#549]
List common causes of various solve() failures, with examples, and suggestions for debugging.

**Comment by bqpd** [comment]
Ooh, great plan.

**Comment by whoburg** [comment]
Also modeling gotchas -- like relaxing an equality where it's not valid to do so. Good example is relaxing the equality `0.5*rho*V**@*CL*S == W`, when `CL` is separately pressured from above in a drag model and from below in a power model, e.g. `P >= V*W*CD/CL`.

**Comment by bqpd** [comment]
It exists! http://gpkit.readthedocs.io/en/latest/advancedcommands.html#debugging

And will be enhanced by the merging of `feasmodtest`.

That said, we could use some discussion of pressures, so I've refocused this issue.
