### ISSUE TITLE
Testing ipyparallel

### ISSUE THREAD

**Issue by galbramc** [convexengineering/gpkit#569]
II notice that you have a bunch of code that runs in parallel if ipyparallel is installed. 
- [ ] Currently this is not tested in any of the current jenkins tests. Should it be?
- [ ] Should the tests be done with and without ipyparallel? 
- [ ] If you want it tested, should it be a separate job or can we add it to the existing ones?

**Comment by bqpd** [comment]
Hmm! @whoburg? I think I'm the only one who's done any parallel sweeps so far.

**Comment by whoburg** [comment]
I think testing this is a great idea. I guess the first question is, do any of our current unit tests exercise this functionality?

**Comment by bqpd** [comment]
note ipyparallel is currently broken
