### ISSUE TITLE
unit test gpkit.interactive

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#572]
Let's start brainstorming about what unit tests we could write for `gpkit.interactive`. This is important -- we don't want an update to break controlpanel for our users...

as suggested by @galbramc, https://pypi.python.org/pypi/pytest-ipynb should allow us to test interactive features as well as bugs that only occur in ipython notebooks, such as
- [ ] pint errors raised by `import gpkit` described in #665 
- [ ] #664  (controlpanel for SP)
- [ ] chartJS

**Comment by galbramc** [comment]
matplotlib has a testing infrastructure for [comparing images ](http://matplotlib.org/devel/testing.html#writing-an-image-comparison-test), though this guy suggests [inspecting the figures](http://stackoverflow.com/questions/27948126/how-can-i-write-unit-tests-against-code-that-uses-matplotlib).

for ipywidges you might look at what the [authors do](https://github.com/ipython/ipywidgets/tree/master/ipywidgets/widgets/tests)
