### ISSUE TITLE
force united substitutions

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#583]
Carry-over from #579. We currently allow the following:

``` python
L = Variable("L", "ft", "length")
L.sub(20)  # results in gpkit.Monomial(20 [ft])
```

This is a proposal to have the above raise a `ValueError` or `DimensionalityError`, thereby requiring substitutions to have correct units.

below is some previous commentary backing up this position.
###### 

It's just dangerous. For example, say there's a quantity L in a results table that I want to show in ft (currently in meters). My current method for accomplishing that is to change the `"m"` `Variable("L", "m", "some length")` call that defines `L` to use `"ft"` instead . But that breaks the model if there's an `L.sub(L, 20)` call somewhere that I miss...
###### 

One more example. Looking in another repo I see a lot of default kwargs in Model inits:

``` python
    def __init__(self, Aeng=np.pi*(1.75/2)**2, CDwm=0.5, clvt=0.5, e=0.8,
                 le=4.83, Lfuse=39, mu=1.4E-5, rho_c=0.38, rho0=1.225,
                 Te=1.29E5, Vc=234, V1=65, xCG=18, **kwargs):
```

I think we want to discourage this, to use substitution instead. But doing so seems dangerous without some units enforcement.
######

**Comment by bqpd** [comment]
@whoburg, curious how you're feeling about this after using gpkit more heavily recently...

**Comment by mayork** [comment]
I agree with the commentary @whoburg posted above. Long story short I had a quantity in km^2 and was using substitutions to substitute it into a variable whose units were m^2 which ended up causing me a lot of problems. it took me a long time to work around the problem...I didn't realize substitutions called mag somewhere under the hood until talking to Woody a few minutes ago.

I would be in favor of the proposal where if you substitute a quantity into a variable and the quantity and the variable have the same dimensions, the unit conversion occurs under the hood. If the dimensions are wrong then an error is thrown.

As far as the length example above... 

L = Variable("L", "ft", "length")
L.sub(20)  # results in gpkit.Monomial(20 [ft])

I don't think it would be bad to throw an error if you just sub a value into a variable with units. I think making the user verify their units is a good way to prevent errors...it might seem a little bit annoying at first, but I think in the long run it would save people debugging time

**Comment by bqpd** [comment]
@mayork great! I was leaning towards doing this in the next release, but it's good to here of a real bug.

**Comment by whoburg** [comment]
I'm actually confused now. @mayork says he did something that boils down to the following:

```python
A5 = Quantity(920.503363345, 'joule ** 0.5 * kilogram ** 0.5 / kilopascal / second')
model.substitutions.update("A_5": A5)
```

... where A5 is a Variable with units of `m^2`... and that in the result A5 was equal to 920.5 instead of the properly-converted-to-m^2 0.9205.

But looking at lines 130 and 131 of `substitution.py`, it looks like we do proper unit conversion when a substitution value is a Quantity. So, @mayork, did you really see this behavior? If so, we have a bug outside this design discussion.

I'll participate in the discussion once we track down what was going on with your example.

**Comment by mayork** [comment]
I recreated what I saw at this commit https://github.com/hoburg/gpkit-models/pull/72/commits/5c965f7d3649fd315eff4c0fcc5fb7bd037537d2

The behavior is observed in the two variables A5 and A7. After running the on design case I do some computations to compute the nozzle sizes, A5 and A7. I printed the two values in two different units each (the weird units are what python gives me normally, i got m^2 with A5.to(m^2)). lines 1 and 2 below are A5, the bottom two are A7. The correct m^2 values are .92 and 4.28 respectively. 
![image](https://cloud.githubusercontent.com/assets/6796415/16394603/1867807a-3c84-11e6-95e2-1b85d0e68460.png)
I then substitute the quantities printed above into the variables A5 and A7 (they live in the OffDesign sub model in engine_components.py).

When I solve the model this is what I see in the solution table
![image](https://cloud.githubusercontent.com/assets/6796415/16394670/5e24da90-3c84-11e6-9653-03dc4fbd97cd.png)
so it appears somewhere there is a unit conversion that is not occurring

**Comment by mayork** [comment]
I just ran into this again with this commit https://github.com/hoburg/gpkit-models/pull/73/commits/21976d15d7bab74db95743a75c050fa0685629a5. I have this substitution 

'thrust': 40000*units('lbf'),

and when I solve it I get that thrust equals 40,000 N not 40,000 lbf

**Comment by whoburg** [comment]
ok thanks for the great debugging info @mayork

**Comment by bqpd** [comment]
So the solutions are right but not printing correctly?

**Comment by mayork** [comment]
Yes, I believe that is what's happening

**Comment by mayork** [comment]
@whoburg this is what was happening in the model I just showed you...

I just ran into this again...it's pretty confusing

**Comment by bqpd** [comment]
I think this needs a new issue.

**Comment by whoburg** [comment]
Ok that unit printing bug is captured in #809; this ticket reverts to a design discussion re: what substitutions should be allowed for united quantities.

**Comment by bqpd** [comment]
Should we force quantity substitutions in 0.6?

**Comment by whoburg** [comment]
I'm open to either decision on this design discussion.

For myself, I prefer quantity substitutions because they are less likely to lead to unintended units errors.

Pro of enforcing this is encouraging (well ok, requiring) what I see as a good coding practice.

**Comment by bqpd** [comment]
note: implement this before v0.8
