### ISSUE TITLE
Document when to inherit from ConstraintSet vs Model

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#607]
Re https://github.com/hoburg/gpkit-models/pull/45#issuecomment-201454600

**Comment by whoburg** [comment]
also need clear documentation on readthedocs explaining this

**Comment by bqpd** [comment]
By now, it's just: inherit from Model if you'll have a cost and want the user to be able to sweep and call `solve`/`debug` etc

**Comment by whoburg** [comment]
It used to be that Models got model names attached, whereas ConstraintSets did not, and this caused different linking behavior. Has that changed?

**Comment by bqpd** [comment]
Oh, yeah. But that'll change with NamedConstraintSet.

Capabilities:
  - Model
    - sweep, solve, localsolve, and naming as below
  - NamedConstraintSet
    - named (by default based on class name)

For everything else, there's ConstraintSet.
