### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#628]
Ported over from hoburg/gpkit-models#58 [and later edited by @bqpd]
- [ ] Is default.latex living in any of our git repos? Let's decide where it belongs and get it under version control.
- [ ] Did we ever get your markdown makefile / shell script added to gpkit or gpkit-models?
- [ ] The latex output is still shoddy, largely due to hoburg/gpkit#480, hoburg/gpkit#560, hoburg/gpkit#561, and hoburg/gpkit#562.
    - [ ] default latex output should be good enough for @mjburton11 
- [ ] Create a simple script or framework for causing markdown models like the one in this PR to appear on our gpkit-models readthedocs (once merged to master).
- [ ] Re: the checkpoint above, it would be especially nice if the html models on readthedocs had a small link to "download PDF" (since we're making it anyway)

**Comment by bqpd** [comment]
No-one is currently using markdown, and the new docstring parsing makes it much more comparable to just reading the python file...
