### ISSUE TITLE
Create new error classes

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#629]
A couple of times now I'm seeing `ValueErrors` caught when they shouldn't be because we use that type of error too much in the code. We should create new errors and use them instead!

**Comment by whoburg** [comment]
sounds good, as long as we don't go overboard with the new error classes -- I like that we currently use standard library Exception types.

**Comment by bqpd** [comment]
Check out what I've done in #629 so far.

**Comment by bqpd** [comment]
Moved to Middle Release to leave time for the design discussion.

**Comment by bqpd** [comment]
Potential errors which could be specialized:

Tightness
Substitution Conflict
Linking Conflict

Solver statuses(Primal Infeasible,  Dual Infeasible Unknown)

**Comment by bqpd** [comment]
`InvalidGPConstraint` has proven to be very useful, here's to more such!
