### ISSUE TITLE
latexpdf documentation doesn't build on all machines

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#698]
According to https://github.com/hoburg/gpkit/commit/add9d6093bc48e4ae21b5378fe0b60b4d6715e2c#commitcomment-17230653

**Comment by whoburg** [comment]
Also, `make latexpdf` now results in an error,

```
rm source/autodoc/*
sphinx-apidoc ../gpkit -o source/autodoc
Creating file source/autodoc/gpkit.rst.
Creating file source/autodoc/gpkit.constraints.rst.
Creating file source/autodoc/gpkit.interactive.rst.
Creating file source/autodoc/gpkit.nomials.rst.
Creating file source/autodoc/gpkit.tests.rst.
Creating file source/autodoc/gpkit.tools.rst.
Creating file source/autodoc/modules.rst.
sed -i '1i Glossary\n********\n\n*For an alphabetical listing of all commands, check out the* :ref:`genindex`\n' source/autodoc/gpkit.rst
sed: 1: "source/autodoc/gpkit.rst": bad flag in substitute command: 'c'
make: *** [apidoc] Error 1
```

**Comment by whoburg** [comment]
argh, seems to not work even several commits back -- need pdf documentation to be working

**Comment by bqpd** [comment]
Mac sed has different syntax :cry:

**Comment by whoburg** [comment]
Sed issue is resolved; changing this issue to capture the fact that we cannot currently `make latexpdf` (latex runs for awhile and then throws an error about nested too deeply)

**Comment by whoburg** [comment]
@bqpd, for working on docs, this is a priority issue so that we can build the pdf output

**Comment by bqpd** [comment]
You can download the latest pdf from the readthedocs page

**Comment by whoburg** [comment]
great, looking forward to figuring out what's going on with the latex build on my machine, and thanks for the tip on downloading the PDF from readthedocs.
