### ISSUE TITLE
Warning when trying to substitute for something that's not present

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#764]
I think it might be nice if a warning is thrown when you try to use subinplace with a varkey or variable name that doesn't exist. I know a few times I made typos in the subinplace and was confused on why things weren't working, this would speed up the debugging process.

**Comment by whoburg** [comment]
👍 . I seem to remember we already talked about doing this, but I can't find that ticket so let's keep this and plan to do it.

Not just for `subinplace` -- I think the behavior should remain consistent across all forms of substitution.

**Comment by aechevarria1** [comment]
Gonna take a look at this

**Comment by aechevarria1** [comment]
I was thinking we could put something in like this to check for any Variables that don't exist in the `substitution` method. Thoughts?
``` python
if not all([True for i,j in enumerate(substitutions) if 'j' in globals() and ('i' in globals() or isinstance('i',(int,float,long)))]):
        raise NameError("a Variable or Varkey does not exist")
```

**Comment by whoburg** [comment]
I think this would be better implemented using Python's set logic (https://docs.python.org/2/library/stdtypes.html#set), and I'm not sure I see the need for using `globals` here.

I think the original suggestion was for an error when a variable does not exist in the model, not when it does not exist in globals.

**Comment by mayork** [comment]
Yeah sorry I wasn't super clear, I meant throw an error when a variable isn't in a constraint set

**Comment by aechevarria1** [comment]
Okay, so I was thinking for this we could put something like this in the Signomial class
``` python
def test(cost,const):
    var_set = set() #set of 
    for i in cost.exps:
        var_set.update(i.keys())
    for j in const:
        if len(j.left.exp) != 0:
            var_set.update([j.left.exp.keys()[0]])
        if len(j.right.exp) != 0:
            var_set.update([j.right.exp.keys()[0]])
```
Then call it in the Model class when a model is getting initialized. This way we can put the variables in the constraint set while initializing a model and check if any variable getting substituted is in said constraint set when called in the Signomial class. Would this implementation be effective?

**Comment by bqpd** [comment]
This can be done for free in the substitution logic, so I'd do it in there.

**Comment by aechevarria1** [comment]
So is there a way or purpose to sub in a `Variable` into a model or signomial after already subbing in a numerical value, so something like

`m.subinplace("x",5)`

then later

`m.subinplace("x",x)`

I am wondering if there even needs to be a `set` within the model of signomial, if not, we could just have

``` python
for sub_varkey in substitutions:
	    if sub_varkey not in nomial.varkeys:
    		     raise NameError("Varkey, Variable, or String does not exist in the Nomial")
```

to check if the variable being substituted is in the constraint set

**Comment by bqpd** [comment]
No, you can't undo a subinplace; you have to do a regular substitution if you want to keep the original.

**Comment by bqpd** [comment]
The `suball` branch (https://github.com/hoburg/gpkit/tree/suball) contains a simple check for this, but it should maybe be only used for user's calls to sub/subinplace.

**Comment by bqpd** [comment]
Our current design decision is to no raise this warning, and to keep a giant substitutions dictionary around. If this were to be implemented, it should be combined with the proper routing of substitutions to constraintsets during a solve, such that that doesn't have to form an exception.

**Comment by bqpd** [comment]
This is incompatible with certain uses of linked variables.
