### ISSUE TITLE
getting gpkit onto athena

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#766]
I tried to install gpkit on athena so I could use Mosek and am getting this error when I run

```
pip install ctypesgen --pre
```

```
copying and adjusting ctypesgen.py -> build/scripts-2.7

changing mode of build/scripts-2.7/ctypesgen.py from 644 to 755

running install_lib

creating /usr/local/lib/python2.7/dist-packages/ctypesgencore

error: could not create '/usr/local/lib/python2.7/dist-packages/ctypesgencore': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_mayork/ctypesgen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xGQCrn-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_mayork/ctypesgen
Storing debug log for failure in /afs/athena.mit.edu/user/m/a/mayork/.pip/pip.log
mayork@W20-575-45:~$ ^C
mayork@W20-575-45:~$ 
```

I'm an extreme amateur with athena, but it looks like the normal user doesn't have access to install these items. I feel like getting gpkit onto athena could be useful, possibly something to look into.

**Comment by mayork** [comment]
same problem occurs when running ```pip install cvxopt```

**Comment by bqpd** [comment]
You should create a virtualenv to install gpkit in :) definitely worth
mentioning in the tutorial

**Comment by mayork** [comment]
ah I see, had no idea that existed. I'll give it another try

**Comment by mayork** [comment]
hmm I still can't get this to work. spent quite some time and I think its a combination of my general low level of familiarity and the virtual environment...whenever I try and run mosek -f nothing happens, even after I thought I set the path variable. I also get no installed solver when I run the gpkit tests
