### ISSUE TITLE
signomial localsolve with dual infeasibility

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#769]
When an iteration of solving an SP is dual infeasible, we should raise that to the user, instead of running a (primal) infeasibility iteration.

An example that is currently dual infeasible on the first iteration but then goes on to an infeasibility solve is on the `commercial_sizing` branch of gpkit-models, at commit 386de4077ce9e0786087ae5b6c2ea4fa310538e5, in the file `gpkitmodels/Commercial Sizing/Commerical_Flight_Profile.py`. Run with mosek for speed and to see the dual infeasibility.

**Comment by bqpd** [comment]
This is now done in https://github.com/convexengineering/gpkit/pull/1463 (even before the introduction of pccpsolve as the new default)
