### ISSUE TITLE
Signomial Program moves from valid suboptimal solution to worse solutions 

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#803]
MWE:

``` python
from gpkit import Variable, Model, SignomialsEnabled
from gpkit.constraints.tight import Tight as TCS

h = Variable("h", "mm", "vertical thickness")
H = Variable("H", 20, "cm", "opening height")
b = Variable("b", "mm", "horizontal thickness")
bscale = Variable("b_{scale}", 1, "-")
hscale = Variable("h_{scale}", 1, "-")
B = Variable("B", 10, "cm", "total width")
x_cg = Variable("x_{CG}", "cm", "x distance from far side of vertical beam to cg")
x_cg_max = Variable("x_{CG}_max", 100, "cm", "x distance from far side of vertical beam to cg")
x_cg_m_Bd = Variable("x_{CG}mbd", "cm", "x distance from far side of vertical beam to cg")
Ixx = Variable("I_{xx}", "cm^4", "x moment")
Iyy = Variable("I_{yy}", "cm^4", "y moment")
Ixxmin = Variable("I_{xx, min}", 10, "cm^4", "x moment")
Iyymin = Variable("I_{yy, min}", 10, "cm^4", "y moment")
A = Variable("A", "cm^2", "spar area")


with SignomialsEnabled():
    constraints = [
        x_cg <= x_cg_max,
        x_cg * A >= 2*(h*hscale)*B**2/2 + (b*bscale)**2*H/2,
        Ixx <= H**3*(b*bscale)/12. + 2*((h*hscale)**3*B/12. + (h*hscale)*B*((h*hscale)+H)**2/4.),
        Iyy <= (b*bscale)**3*H/12 + (b*bscale)*H*(x_cg-(b*bscale)/2)**2+ 2*B**3*(h*hscale)/12+ 2*B*(h*hscale)*(x_cg - B/2)**2,
        A >= 2*B*(h*hscale) + H*(b*bscale),
        Ixx >= Ixxmin,
        Iyy >= Iyymin,
         ]


sp = Model(A, TCS(constraints, reltol=1e-4)).sp()
result = {"variables": {k: 1 for k in sp.varkeys}}
```
and then in a separate cell run 

``` python
result = sp.gp(x0=result["variables"]).solve()
print result["cost"]
```

and you can watch it do this:

![image](https://cloud.githubusercontent.com/assets/1482776/17453883/f555619a-5b39-11e6-95df-5013f7f40aeb.png)

 By changing bscale you can do what the solver should be doing. At a bscale of 0.1 you can get a better optimal result:

![image](https://cloud.githubusercontent.com/assets/1482776/17453893/516979b2-5b3a-11e6-8eeb-8e692cc97cf6.png)

But that might just be a scaling issue; should we be scaling SP inputs? Regardless, the bounce of the first graph is concerning.

**Comment by whoburg** [comment]
interesting! @bqpd, want to post the code to reproduce the plots too?

**Comment by bqpd** [comment]
Sure:

```python
result = sp.program.gps[0].result
result = {"variables": {k: 1 for k in result["variables"]}}
costs = []
```
```python
result = spp.gp(x0=result["variables"]).solve()
B, b, H, h = map(lambda k: result["variables"][k], "BbHh")
A = 2*B*h + H*b
x_cog = (h*B**2 + b**2*H/2)/(2*B*h + H*b)
Ixx = H**3*b/12. + 2*(h**3*B/12. + h*B*(h+H)**2/4.)
Iyy = b**3*H/12 + b*H*(x_cog-b/2)**2+ 2*B**3*h/12+ 2*B*h*(x_cog - B/2)**2
costs.append(result["cost"])
print
print result["cost"], Iyy, A, result["variables"]["A"]
```
```python
%pylab inline
figure(figsize=(8,8))
plot(array(costs[:11]))
ylabel("area [cm^2]")
xlabel("iterations")
```

**Comment by bqpd** [comment]
@pgkirsch, you've seen this one?

**Comment by pgkirsch** [comment]
Yikes...that's not good!

**Comment by bqpd** [comment]
- [ ] we check in SP solves that the cost really is getting lower
- [ ] why is this happening

**Comment by whoburg** [comment]
slightly modified the MWE (imports and deleted one line) to make it actually run

**Comment by whoburg** [comment]
yeah, with no equalities it should not be possible for the cost to increase from one iteration to the next, so this is quite surprising / concerning.

**Comment by mayork** [comment]
@bqpd ever have any ideas as to what this is? I can see similar results in a model with some signomial equalities, but it's possible it is just due to the equalities...

**Comment by bqpd** [comment]
I haven't tested whether the non-equality containing code above still has that behavior, but if it does it's a clear violation of how SPs without equalities should behave.

**Comment by bqpd** [comment]
No longer happens after I added an upper bound to x_cg (as prompted by our new dual-feasibility checker). Still a weird thing to happen, though!
