### ISSUE TITLE
should all Nomial.__eq__ return constraints, not just between monomials?

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#824]
@whoburg in #818 

> BTW, this is making me wonder whether we should implement `Nomial.__eq__`to return a Constraint (consistent with other operators we've overloaded), and then call for `__nonzero__` when we explicitly want it, e.g. in unit tests. This is clearly a separate design discussion though.

If this is done, as part of it we should implement https://github.com/convexengineering/gpkit/issues/956

**Comment by whoburg** [comment]
Some further detail on how this proposal would work:

`Nomial.__eq__` would try to create a Constraint, which will usually lead to raising an Exception. There are two cases where an Exception would not be raised:

1. If both Nomials are Monomials, in which case a `MonomialEquality` constraint will be returned.
2. Inside a `SignomialsEnabled` environment, in which case a `SignomialEquality` constraint will be returned.

Testing whether two Nomial objects are the same would be accomplished by a method other than `__eq__`, e.g. `Nomial.equivalent_to(other)`.

`Constraint.__nonzero__` behavior would be up for discussion -- we could use the current 0 means not always-true and 1 means always-true, or switch to something more pythonic like 1 for "there's a non empty constraint here", and then implement `Constraint.always_true()` that returns a bool.
