### ISSUE TITLE
constant exponent variables

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#825]
I think a critical addition to the engine code is to allow variables in the exponent. Not free variables, but constants. Maybe make a class called ExpVariable to make the distinction very clear. The advantage here is being able to use substitutions and calculate sensitivties to constants in an exponent. Component efficiencies are in the exponent of the isentropic relation, which is the major motivation behind this issue.

I'm moving into the validation phase of the engine model and having to hard code sensitivities is a major hinderance.

I thought already made this an issue but couldn't find one...if I did feel free to close this.

**Comment by mayork** [comment]
if this could be a priority it would really help me close out the engine model

**Comment by whoburg** [comment]
I agree, it is common for constants to appear both in exponents and in the usual way (e.g. in atmosphere model), and we should report those sensitivities correctly. This could also be useful for gauging sensitivity to exponent values in fitted models.

@bqpd, what will this take?

To be clear, I do not support free exponent values -- just fixed variables.

**Comment by mayork** [comment]
I was also just advocating fixed variables in the exponents...I thought maybe they should have a class constructor with a different name to make this clear?

**Comment by bqpd** [comment]
Hmm. I don't think this will take too much; we can keep notice of such exps in the varlocs and varkeys, and substitute them normally. Hmm. But it might get a little hairy with mmaps.

**Comment by bqpd** [comment]
But it is a modification pretty deep in the code, so it'll take some focused time.

**Comment by mayork** [comment]
were there any updates on this?

**Comment by bqpd** [comment]
Not currently targeted for the next release, unless you can convince @whoburg

**Comment by mayork** [comment]
@whoburg I think having this ability would really add to the engine model (particularly having the sensitivities to component polytropic efficiencies)...I think it could be worth building this functionality sooner rather than later for the engine paper (its also needed to get more accurate engine validation cases)

**Comment by bqpd** [comment]
Saw this recently in the shopping model as well...this should definitely happen, although it may not be before January.

**Comment by whoburg** [comment]
I support

**Comment by 1ozturkbe** [comment]
Aight this is going to happen now, because I would like to have sensitivities to exponents for robust. If interested, follow the varexp branch.

**Comment by 1ozturkbe** [comment]
Addressed in #1438 .
