### ISSUE TITLE
A better way of comparing models

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#829]
when trying to debug #827 we discovered it would be nice to have an automated way to get a diff between two GPs...doing it manually for large models appears as though it'll be cumbersome

**Comment by mayork** [comment]
I think it wouldn't be too hard to automate what I just did to get the long comment in #827...maybe just a run a diff on the .constraints, .exps, .p_idxs, .cs, and .varlocs and either print them to the screen or write each one to a text file. thoughts?

**Comment by bqpd** [comment]
I'm provisionally interested (I find myself doing the same thing every so often) but worried that it would be a hard tool to make easy to use with the A matrix (which is ultimately where the differences are passed to the solver).

**Comment by bqpd** [comment]
@pgkirsch said in #916:

One thing I am often interested in is how the solution of a model changes when I add constraints/change subsitutions/use different sub-models etc.

My current way of tracking this is to create a .sol that I update and commit each time I make a change (and a git pre-commit hook ensures I don't forget to update the .sol each time I commit). git diff then allows me to see what has changed, and by how much.

This method is somewhat rudimentary and definitely not perfect. It would be nice to have something that does this more elegantly, and had other features, for example showing percentage changes of each variable, and even ranking the variables by percentage change. I think a git-centric solution might be the way to do it, but I am open to other suggestions.

**Comment by pgkirsch** [comment]
I just discovered the beauty of pickle, and I have a feeling that a good solution for comparing the solutions of two models (one old, one new) involves using it. Unfortunately, pickle doesn't seem to work with `SolutionArray` types (issue to follow).

p.s. @bqpd I'm not convinced that there aren't two distinct issues here (i.e. #829 and #916). I think #829 is about comparing two GPs without solving, whereas #916 is specifically about comparing solutions.

**Comment by bqpd** [comment]
@pgkirsch good point! reopening.
