### ISSUE TITLE
document that SP formulation affects solving

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#862]
re #406, where dividing by `Re`, instead of subtracting it, allowed a model to solve.

**Comment by whoburg** [comment]
#406 seems to have disappeared from github?

**Comment by bqpd** [comment]
WEIRD

**Comment by bqpd** [comment]
@1ozturkbe, this may have been an example of a model that became infeasible without an initial SP guess, but it was a pretty complex model.
