### ISSUE TITLE
latex for vectors, products and elementwise operations

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#87]
from 
![gif latex](https://cloud.githubusercontent.com/assets/1482776/4708077/e593260c-5893-11e4-9dd7-35e0e78f8b4a.gif)
to
![gif latex](https://cloud.githubusercontent.com/assets/1482776/4708071/d9d79870-5893-11e4-87f2-62e54ca33ca5.gif)
and from 
![gif latex](https://cloud.githubusercontent.com/assets/1482776/4708103/33c3584c-5894-11e4-8c08-4a9ba7bb1bdc.gif)
to
![gif latex](https://cloud.githubusercontent.com/assets/1482776/4708113/46b10a62-5894-11e4-8b9b-4657ca640a1e.gif)

**Comment by whoburg** [comment]
Latex printing is looking particularly ugly for me on the latest version of iPython notebook. 

Code to reproduce:
```python
from gpkit import Variable, VectorVariable
import gpkit.interactive
gpkit.interactive.init_printing()
v = Variable('v')
x = VectorVariable(3, 'x')
v*x
```
Mix of subscripted and not subscripted parens...

**Comment by whoburg** [comment]
* [ ] It would be nice if gpkit.interactive exposed a method for pretty-printing, just once, without calling `init_printing()` (and therefore affecting all output). I might want to see plain text output in most cases, but pretty print a `GP`, for example.

**Comment by bqpd** [comment]
Yeah! That should definitely be doable with the notebook's "Latex()" output
command.

**Comment by bqpd** [comment]
This latex bug (why is it in this issue and not a new one?) showed up after your merged PR. Tracking it down...

**Comment by bqpd** [comment]
It seems that changing the `_latex` method to `latex` is what caused the bug. Shucks.

**Comment by whoburg** [comment]
Shucks indeed (and sorry for causing that bug).

Going back to the original intent of the ticket -- I like the simplified printing for vectors (where all elements have the same exponents), but I'm not so convinced that the product (pi) notation is good. Maybe, but I worry it could cause unwarranted confusion.

**Comment by bqpd** [comment]
Should it be part of the 0.2.0 milestone, then?

**Comment by whoburg** [comment]
I don't think it needs to be part of the milestone. (Fine to include if easy, but not a priority). My reasoning is 1)  we have more critical items to accomplish as part of 0.2.0, and 2) this is unlikely to affect the API.

**Comment by bqpd** [comment]
Sounds good!

**Comment by bqpd** [comment]
init_printing isn't necessary anymore (hasn't been for some time). What's the priority on the rest of these latex improvements?

**Comment by whoburg** [comment]
looking back, the original post suggested two things: 

1. consolidating terms with like powers
2. not printing every element of a vector constraint

In my opinion, 2. is useful and should probably be done, whereas 1. is extremely low priority.

**Comment by bqpd** [comment]
We have 2 now!
