### ISSUE TITLE
A better way of comparing solutions

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#916]
One thing I am often interested in is how the solution of a model changes when I add constraints/change subsitutions/use different sub-models etc.

My current way of tracking this is to create a .sol that I update and commit each time I make a change  (and a git pre-commit hook ensures I don't forget to update the .sol each time I commit). `git diff` then allows me to see what has changed, and by how much.

This method is somewhat rudimentary and definitely not perfect. It would be nice to have something that does this more elegantly, and had other features, for example showing percentage changes of each variable, and even ranking the variables by percentage change. I think a git-centric solution might be the way to do it, but I am open to other suggestions.

**Comment by bqpd** [comment]
Great! This is a great way of describing it. Another issue on the same topic is #829, so I'll move your comment there.

**Comment by bqpd** [comment]
Reopened because this is specifically about comparing solutions.
