### ISSUE TITLE
Overloading += for weight/cost breakdowns

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#919]
It might be nice to add a feature that allows you to add to a weight breakdown on the fly, and the `+=` operator seems like an elegant way of achieving this.

e.g.:

``` python
W += W_{wing}
W += W_{fuse},
.....
.....
......
`W += W_{payload}`
```

The use case for this is when I have a sub-model that adds a variable (e.g. `W_{payload}`) to the weight breakdown, but that variable doesn't exist outside of the sub-model, so when the sub-model is not used it doesn't make sense to include it in a weight breakdown.

Of course, one workaround is to include a modified weight breakdown in the submodel (e.g. `W >= W_{wing} + W_{fuse} + W_{pay}`) and the "nominal" weight breakdown will be slack, but there are a number of reasons why this is somewhat nasty.

Under the hood, the `+=` operator would, when first used, create a constraint `W >= W_{wing}` and tag it somehow, so that when `W +=` is called again, it adds the next constituent weight to the same constraint.

This is just a sketch of an idea, open to better suggestions and/or being told why this is a bad idea.

**Comment by bqpd** [comment]
Love it. Even easier way to do creation would be not to even make a
posynomial until `as_posyslt1()` is called, instead just storing the
monomial list.

**Comment by bqpd** [comment]
@mjburton11, do you have thoughts about this as it might relate to SummingConstraintSet?

**Comment by mjburton11** [comment]
I think this is a great idea.  I have two ideas that I think are related.  In the `jho` model I have multiple sub classes that each have a weight variable, `W`.  The sub classes, or components don't really interact with each other until I create the aircraft and add the weights of all the components.  In this case it is really convenient to have a SummingConstraintSet that does that for me. 

The other case that occasionally comes up, is when I create a constraint in a submodel and then need to add an extra term to that constraint.  For example, in my Steady Level Flight model I have thrust equals drag.  But when I create SLF in my Climb model I have to modify it to account for a climb rate.  I'm currently rewriting it and my original constraint goes slack.  It would be nice though to have a way to modify the constraint directly.  Sounds like the `+=` idea could be a possible solution.

**Comment by bqpd** [comment]
Hmm, @mjburton11, reopen if you still think this would be useful
