### ISSUE TITLE
print non-approximated infeasible constraint

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#952]
I just ran into the following: I was getting an infeasible constraint warning and spent about 10 minutes trying to hunt down the constraint (which I didn't remember making)...turns out the infeasible constraint was a signomial inequality and GPkit was printing out the monomial approximation of the signomial. This didn't surprise me, but for users not familiar with how SPs work this could be a very confusing error message

**Comment by bqpd** [comment]
The bigger question might be, how did you get debug running on an SP? :p

**Comment by bqpd** [comment]
Unfortunately because this is printed in `.as_posyslt1()` it doesn't have any straightforward access to the non-approximated constraint.
