### ISSUE TITLE
casting left and right sides of constraints to gpkit types?

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#956]
Re: https://github.com/hoburg/gpkit/pull/938#discussion_r88758599, should we cast the left and right sides of `ArrayConstraint` objects (and `SingleEquationConstraint`s, for that matter) to gpkit objects? This would avoid having to check types when interacting with `constraint.left` and `constraint.right`.

**Comment by bqpd** [comment]
We can't do this for equalities, since `arr == "a"` is valid syntax, so I vote that we should not cast the left and right sides...I think the logic to determine when to cost would be more complex than the logic we have now.

**Comment by whoburg** [comment]
... unless we decide in #824 to always overload `==`, `<=` and `>=` to return Constraints (or raise an error if that's not possible)

**Comment by bqpd** [comment]
Good point!
