### ISSUE TITLE
Speed goals

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#996]
- [x] Large GP solves should build in less time than the solver takes (#479)
  - [x] Fast rebuild of next approximations's GP in SignomialInequality / Equality
  - [ ] Fast rebuild of next sweep point's GP (#678)
  - [ ] Automated profiling of some large examples to keep track of all the above over time

re: #726

**Comment by whoburg** [comment]
added the 4th profiling bullet above

**Comment by whoburg** [comment]
@edfan

**Comment by edfan** [comment]
Finally done with finals & move; ready to start doing things again.

I've been working with Boost::Python at work recently, and might try porting some things to C/C++ to see how performance looks. Will profile again soon to identify targets, but genA() looks promising for a start.

**Comment by bqpd** [comment]
Are you on the `nomialmap` branch?

**Comment by bqpd** [comment]
(there's a fair number of optimizations on that branch, it's just lacking some docstrings and other pylint niceness)

**Comment by edfan** [comment]
Wow, this is amazing- great job! Profile looks amazing.

Hmm, might go after [mono_approximation](https://github.com/hoburg/gpkit/blob/ba6420791a4ede9d274470bdf1af77de9669c62c/gpkit/nomials/math.py#L97) to start (or perhaps the underlying diff & sub functions in NomialMap); seems like a fairly hot loop.

**Comment by edfan** [comment]
One potential roadblock might be that Jenkins will likely not be configured to build the C extension; if Boost/Cython is involved, it might get quite complex, so might be a good idea to stick to the native C extension capabilities for now. Additionally, I'll look into how distribution as a package works (it's clearly possible given numpy/etc, but I'm not sure exactly how to do it).

**Comment by edfan** [comment]
The answer to the above is `distutils.Extension`- seems pretty portable, shouldn't have an issue with pip. No clue on Jenkins.

**Comment by edfan** [comment]
By the way- re: last bullet point in OP- a coworker showed me [this](https://home.apache.org/~mikemccand/lucenebench/indexing.html) today, and it's pretty cool. May try to set something up in the next couple of months.
